#loc1 = loc("cfd_step_factor.cpp":27:6)
#loc8 = loc("./cfd_step_factor.h":10:19)
#loc63 = loc("cfd_step_factor.cpp":5:13)
#loc84 = loc("cfd_step_factor.cpp":12:14)
#loc98 = loc("cfd_step_factor.cpp":17:14)
#loc110 = loc("cfd_step_factor.cpp":22:14)
#loc119 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:3)
module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr, dense<64> : vector<4xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<271>, dense<32> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<270>, dense<32> : vector<4xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<"dlti.stack_alignment", 128 : i32>, #dlti.dl_entry<"dlti.endianness", "little">>, llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu", "polygeist.target-cpu" = "x86-64", "polygeist.target-features" = "+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87", "polygeist.tune-cpu" = "generic"} {
  func.func @workload(%arg0: memref<1024xf32> loc("cfd_step_factor.cpp":27:6), %arg1: memref<5120xf32> loc("cfd_step_factor.cpp":27:6), %arg2: memref<1024xf32> loc("cfd_step_factor.cpp":27:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %cst = arith.constant 5.000000e-01 : f32 loc(#loc2)
    %c4_i32 = arith.constant 4 : i32 loc(#loc3)
    %c3_i32 = arith.constant 3 : i32 loc(#loc4)
    %c2_i32 = arith.constant 2 : i32 loc(#loc5)
    %c1_i32 = arith.constant 1 : i32 loc(#loc6)
    %c5_i32 = arith.constant 5 : i32 loc(#loc7)
    %c1024_i32 = arith.constant 1024 : i32 loc(#loc8)
    %c0_i32 = arith.constant 0 : i32 loc(#loc9)
    %true = arith.constant true loc(#loc10)
    %c1 = arith.constant 1 : index loc(#loc)
    %c2 = arith.constant 2 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc11)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc11)
    %alloca = memref.alloca() : memref<1xf32> loc(#loc12)
    %cast = memref.cast %alloca : memref<1xf32> to memref<?xf32> loc(#loc12)
    affine.store %0, %alloca[0] : memref<1xf32> loc(#loc12)
    %alloca_0 = memref.alloca() : memref<1xf32> loc(#loc13)
    %cast_1 = memref.cast %alloca_0 : memref<1xf32> to memref<?xf32> loc(#loc13)
    affine.store %0, %alloca_0[0] : memref<1xf32> loc(#loc13)
    %alloca_2 = memref.alloca() : memref<1x3xf32> loc(#loc14)
    %cast_3 = memref.cast %alloca_2 : memref<1x3xf32> to memref<?x3xf32> loc(#loc14)
    %alloca_4 = memref.alloca() : memref<1xf32> loc(#loc15)
    %cast_5 = memref.cast %alloca_4 : memref<1xf32> to memref<?xf32> loc(#loc15)
    affine.store %0, %alloca_4[0] : memref<1xf32> loc(#loc15)
    %alloca_6 = memref.alloca() : memref<1x3xf32> loc(#loc16)
    %cast_7 = memref.cast %alloca_6 : memref<1x3xf32> to memref<?x3xf32> loc(#loc16)
    %alloca_8 = memref.alloca() : memref<1xf32> loc(#loc17)
    %cast_9 = memref.cast %alloca_8 : memref<1xf32> to memref<?xf32> loc(#loc17)
    affine.store %0, %alloca_8[0] : memref<1xf32> loc(#loc17)
    %1 = "polygeist.undef"() : () -> i32 loc(#loc18)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc19)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            %2 = scf.if %true -> (i32) {
              %4 = scf.execute_region -> i32 {
                scf.yield %c0_i32 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %4 : i32 loc(#loc)
            } else {
              scf.yield %1 : i32 loc(#loc)
            } loc(#loc)
            %3:2 = scf.while (%arg3 = %0, %arg4 = %2) : (f32, i32) -> (f32, i32) {
              %4 = arith.cmpi slt, %arg4, %c1024_i32 : i32 loc(#loc20)
              scf.condition(%4) %arg3, %arg4 : f32, i32 loc(#loc21)
            } do {
            ^bb0(%arg3: f32 loc("./cfd_step_factor.h":10:19), %arg4: i32 loc("./cfd_step_factor.h":10:19)):
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = arith.muli %arg4, %c5_i32 : i32 loc(#loc22)
                      %7 = arith.index_cast %6 : i32 to index loc(#loc23)
                      %8 = "polygeist.subindex"(%arg1, %7) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc24)
                      %9 = affine.load %8[0] : memref<?xf32> loc(#loc24)
                      affine.store %9, %alloca_8[0] : memref<1xf32> loc(#loc17)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc25)
                  %7 = "polygeist.subindex"(%6, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc25)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc26)
                  %9 = arith.addi %8, %c1_i32 : i32 loc(#loc27)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc28)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc29)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc29)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc30)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc31)
                  %7 = "polygeist.subindex"(%6, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc31)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc32)
                  %9 = arith.addi %8, %c2_i32 : i32 loc(#loc33)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc34)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc35)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc35)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc36)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc37)
                  %7 = "polygeist.subindex"(%6, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc37)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc38)
                  %9 = arith.addi %8, %c3_i32 : i32 loc(#loc39)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc40)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc41)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc41)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc42)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = arith.muli %arg4, %c5_i32 : i32 loc(#loc43)
                      %7 = arith.addi %6, %c4_i32 : i32 loc(#loc44)
                      %8 = arith.index_cast %7 : i32 to index loc(#loc45)
                      %9 = "polygeist.subindex"(%arg1, %8) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc46)
                      %10 = affine.load %9[0] : memref<?xf32> loc(#loc46)
                      affine.store %10, %alloca_4[0] : memref<1xf32> loc(#loc15)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  func.call @compute_velocity(%cast_9, %cast_7, %cast_3) : (memref<?xf32>, memref<?x3xf32>, memref<?x3xf32>) -> () loc(#loc47)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = func.call @compute_speed_sqd(%cast_3) : (memref<?x3xf32>) -> f32 loc(#loc48)
                      affine.store %6, %alloca_0[0] : memref<1xf32> loc(#loc13)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = func.call @compute_pressure(%cast_9, %cast_5, %cast_1) : (memref<?xf32>, memref<?xf32>, memref<?xf32>) -> f32 loc(#loc49)
                      affine.store %6, %alloca[0] : memref<1xf32> loc(#loc12)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              %4 = scf.if %true -> (f32) {
                %6 = scf.execute_region -> f32 {
                  %7 = scf.if %true -> (f32) {
                    %8 = scf.execute_region -> f32 {
                      %9 = func.call @compute_speed_of_sound(%cast_9, %cast) : (memref<?xf32>, memref<?xf32>) -> f32 loc(#loc50)
                      scf.yield %9 : f32 loc(#loc)
                    } loc(#loc)
                    scf.yield %8 : f32 loc(#loc)
                  } else {
                    scf.yield %arg3 : f32 loc(#loc)
                  } loc(#loc)
                  scf.yield %7 : f32 loc(#loc)
                } loc(#loc)
                scf.yield %6 : f32 loc(#loc)
              } else {
                scf.yield %arg3 : f32 loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = arith.index_cast %arg4 : i32 to index loc(#loc51)
                  %7 = "polygeist.subindex"(%arg0, %6) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc52)
                  %8 = "polygeist.subindex"(%arg2, %6) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc53)
                  %9 = affine.load %8[0] : memref<?xf32> loc(#loc53)
                  %10 = func.call @_ZSt4sqrtf(%9) : (f32) -> f32 loc(#loc54)
                  %11 = affine.load %alloca_0[0] : memref<1xf32> loc(#loc55)
                  %12 = func.call @_ZSt4sqrtf(%11) : (f32) -> f32 loc(#loc56)
                  %13 = arith.addf %12, %4 : f32 loc(#loc57)
                  %14 = arith.mulf %10, %13 : f32 loc(#loc58)
                  %15 = arith.divf %cst, %14 : f32 loc(#loc59)
                  affine.store %15, %7[0] : memref<?xf32> loc(#loc60)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              %5 = scf.if %true -> (i32) {
                %6 = scf.execute_region -> i32 {
                  %7 = arith.addi %arg4, %c1_i32 : i32 loc(#loc61)
                  scf.yield %7 : i32 loc(#loc)
                } loc(#loc)
                scf.yield %6 : i32 loc(#loc)
              } else {
                scf.yield %arg4 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %4, %5 : f32, i32 loc(#loc21)
            } loc(#loc8)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc62)
  } loc(#loc1)
  func.func @compute_velocity(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":5:13), %arg1: memref<?x3xf32> loc("cfd_step_factor.cpp":5:13), %arg2: memref<?x3xf32> loc("cfd_step_factor.cpp":5:13)) attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %c2 = arith.constant 2 : index loc(#loc)
    %c1 = arith.constant 1 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc64)
    %true = arith.constant true loc(#loc65)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc66)
        %1 = "polygeist.subindex"(%0, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc66)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc67)
        %3 = "polygeist.subindex"(%2, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc67)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc64)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc68)
        %6 = arith.divf %4, %5 : f32 loc(#loc69)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc70)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc71)
        %1 = "polygeist.subindex"(%0, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc71)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc72)
        %3 = "polygeist.subindex"(%2, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc72)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc73)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc74)
        %6 = arith.divf %4, %5 : f32 loc(#loc75)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc76)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc77)
        %1 = "polygeist.subindex"(%0, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc77)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc78)
        %3 = "polygeist.subindex"(%2, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc78)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc79)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc80)
        %6 = arith.divf %4, %5 : f32 loc(#loc81)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc82)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc83)
  } loc(#loc63)
  func.func @compute_speed_sqd(%arg0: memref<?x3xf32> loc("cfd_step_factor.cpp":12:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %c2 = arith.constant 2 : index loc(#loc)
    %c1 = arith.constant 1 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc85)
    %true = arith.constant true loc(#loc86)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc86)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = "polygeist.subindex"(%arg0, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc87)
            %6 = "polygeist.subindex"(%5, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc87)
            %7 = affine.load %6[0] : memref<?xf32> loc(#loc85)
            %8 = arith.mulf %7, %7 : f32 loc(#loc88)
            %9 = "polygeist.subindex"(%5, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc89)
            %10 = affine.load %9[0] : memref<?xf32> loc(#loc90)
            %11 = arith.mulf %10, %10 : f32 loc(#loc91)
            %12 = arith.addf %8, %11 : f32 loc(#loc92)
            %13 = "polygeist.subindex"(%5, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc93)
            %14 = affine.load %13[0] : memref<?xf32> loc(#loc94)
            %15 = arith.mulf %14, %14 : f32 loc(#loc95)
            %16 = arith.addf %12, %15 : f32 loc(#loc96)
            scf.yield %16 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc97)
  } loc(#loc84)
  func.func @compute_pressure(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":17:14), %arg1: memref<?xf32> loc("cfd_step_factor.cpp":17:14), %arg2: memref<?xf32> loc("cfd_step_factor.cpp":17:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %cst = arith.constant 5.000000e-01 : f32 loc(#loc99)
    %cst_0 = arith.constant 0.399999976 : f32 loc(#loc100)
    %true = arith.constant true loc(#loc101)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc101)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = affine.load %arg1[0] : memref<?xf32> loc(#loc102)
            %6 = affine.load %arg0[0] : memref<?xf32> loc(#loc103)
            %7 = arith.mulf %6, %cst : f32 loc(#loc104)
            %8 = affine.load %arg2[0] : memref<?xf32> loc(#loc105)
            %9 = arith.mulf %7, %8 : f32 loc(#loc106)
            %10 = arith.subf %5, %9 : f32 loc(#loc107)
            %11 = arith.mulf %10, %cst_0 : f32 loc(#loc108)
            scf.yield %11 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc109)
  } loc(#loc98)
  func.func @compute_speed_of_sound(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":22:14), %arg1: memref<?xf32> loc("cfd_step_factor.cpp":22:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %cst = arith.constant 1.400000e+00 : f32 loc(#loc111)
    %true = arith.constant true loc(#loc112)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc112)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = affine.load %arg1[0] : memref<?xf32> loc(#loc113)
            %6 = arith.mulf %5, %cst : f32 loc(#loc114)
            %7 = affine.load %arg0[0] : memref<?xf32> loc(#loc115)
            %8 = arith.divf %6, %7 : f32 loc(#loc116)
            %9 = func.call @_ZSt4sqrtf(%8) : (f32) -> f32 loc(#loc117)
            scf.yield %9 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc118)
  } loc(#loc110)
  func.func @_ZSt4sqrtf(%arg0: f32 loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:3)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %true = arith.constant true loc(#loc120)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc121)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = math.sqrt %arg0 : f32 loc(#loc122)
            scf.yield %5 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc123)
  } loc(#loc119)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("cfd_step_factor.cpp":55:27)
#loc3 = loc("./cfd_step_factor.h":32:41)
#loc4 = loc("cfd_step_factor.cpp":47:55)
#loc5 = loc("cfd_step_factor.cpp":46:55)
#loc6 = loc("cfd_step_factor.cpp":45:55)
#loc7 = loc("./cfd_step_factor.h":33:33)
#loc9 = loc("cfd_step_factor.cpp":40:21)
#loc10 = loc("cfd_step_factor.cpp":27:1)
#loc11 = loc("cfd_step_factor.cpp":53:9)
#loc12 = loc("cfd_step_factor.cpp":52:9)
#loc13 = loc("cfd_step_factor.cpp":51:9)
#loc14 = loc("cfd_step_factor.cpp":50:9)
#loc15 = loc("cfd_step_factor.cpp":49:9)
#loc16 = loc("cfd_step_factor.cpp":44:9)
#loc17 = loc("cfd_step_factor.cpp":42:9)
#loc18 = loc("cfd_step_factor.cpp":40:13)
#loc19 = loc("cfd_step_factor.cpp":40:1)
#loc20 = loc("cfd_step_factor.cpp":40:26)
#loc21 = loc("cfd_step_factor.cpp":40:8)
#loc22 = loc("cfd_step_factor.cpp":42:39)
#loc23 = loc("cfd_step_factor.cpp":42:55)
#loc24 = loc("cfd_step_factor.cpp":42:25)
#loc25 = loc("cfd_step_factor.cpp":45:18)
#loc26 = loc("cfd_step_factor.cpp":45:36)
#loc27 = loc("cfd_step_factor.cpp":45:39)
#loc28 = loc("cfd_step_factor.cpp":45:59)
#loc29 = loc("cfd_step_factor.cpp":45:22)
#loc30 = loc("cfd_step_factor.cpp":45:20)
#loc31 = loc("cfd_step_factor.cpp":46:18)
#loc32 = loc("cfd_step_factor.cpp":46:36)
#loc33 = loc("cfd_step_factor.cpp":46:39)
#loc34 = loc("cfd_step_factor.cpp":46:59)
#loc35 = loc("cfd_step_factor.cpp":46:22)
#loc36 = loc("cfd_step_factor.cpp":46:20)
#loc37 = loc("cfd_step_factor.cpp":47:18)
#loc38 = loc("cfd_step_factor.cpp":47:36)
#loc39 = loc("cfd_step_factor.cpp":47:39)
#loc40 = loc("cfd_step_factor.cpp":47:59)
#loc41 = loc("cfd_step_factor.cpp":47:22)
#loc42 = loc("cfd_step_factor.cpp":47:20)
#loc43 = loc("cfd_step_factor.cpp":49:46)
#loc44 = loc("cfd_step_factor.cpp":49:49)
#loc45 = loc("cfd_step_factor.cpp":49:69)
#loc46 = loc("cfd_step_factor.cpp":49:32)
#loc47 = loc("cfd_step_factor.cpp":50:32)
#loc48 = loc("cfd_step_factor.cpp":51:32)
#loc49 = loc("cfd_step_factor.cpp":52:32)
#loc50 = loc("cfd_step_factor.cpp":53:32)
#loc51 = loc("cfd_step_factor.cpp":55:17)
#loc52 = loc("cfd_step_factor.cpp":55:9)
#loc53 = loc("cfd_step_factor.cpp":55:41)
#loc54 = loc("cfd_step_factor.cpp":55:36)
#loc55 = loc("cfd_step_factor.cpp":55:59)
#loc56 = loc("cfd_step_factor.cpp":55:54)
#loc57 = loc("cfd_step_factor.cpp":55:70)
#loc58 = loc("cfd_step_factor.cpp":55:51)
#loc59 = loc("cfd_step_factor.cpp":55:33)
#loc60 = loc("cfd_step_factor.cpp":55:19)
#loc61 = loc("cfd_step_factor.cpp":40:35)
#loc62 = loc("cfd_step_factor.cpp":59:1)
#loc64 = loc("cfd_step_factor.cpp":7:18)
#loc65 = loc("cfd_step_factor.cpp":5:1)
#loc66 = loc("cfd_step_factor.cpp":7:14)
#loc67 = loc("cfd_step_factor.cpp":7:27)
#loc68 = loc("cfd_step_factor.cpp":7:31)
#loc69 = loc("cfd_step_factor.cpp":7:29)
#loc70 = loc("cfd_step_factor.cpp":7:16)
#loc71 = loc("cfd_step_factor.cpp":8:14)
#loc72 = loc("cfd_step_factor.cpp":8:27)
#loc73 = loc("cfd_step_factor.cpp":8:18)
#loc74 = loc("cfd_step_factor.cpp":8:31)
#loc75 = loc("cfd_step_factor.cpp":8:29)
#loc76 = loc("cfd_step_factor.cpp":8:16)
#loc77 = loc("cfd_step_factor.cpp":9:14)
#loc78 = loc("cfd_step_factor.cpp":9:27)
#loc79 = loc("cfd_step_factor.cpp":9:18)
#loc80 = loc("cfd_step_factor.cpp":9:31)
#loc81 = loc("cfd_step_factor.cpp":9:29)
#loc82 = loc("cfd_step_factor.cpp":9:16)
#loc83 = loc("cfd_step_factor.cpp":10:1)
#loc85 = loc("cfd_step_factor.cpp":14:12)
#loc86 = loc("cfd_step_factor.cpp":12:1)
#loc87 = loc("cfd_step_factor.cpp":14:21)
#loc88 = loc("cfd_step_factor.cpp":14:22)
#loc89 = loc("cfd_step_factor.cpp":14:45)
#loc90 = loc("cfd_step_factor.cpp":14:36)
#loc91 = loc("cfd_step_factor.cpp":14:46)
#loc92 = loc("cfd_step_factor.cpp":14:34)
#loc93 = loc("cfd_step_factor.cpp":14:69)
#loc94 = loc("cfd_step_factor.cpp":14:60)
#loc95 = loc("cfd_step_factor.cpp":14:70)
#loc96 = loc("cfd_step_factor.cpp":14:58)
#loc97 = loc("cfd_step_factor.cpp":15:1)
#loc99 = loc("cfd_step_factor.cpp":19:65)
#loc100 = loc("cfd_step_factor.cpp":19:26)
#loc101 = loc("cfd_step_factor.cpp":17:1)
#loc102 = loc("cfd_step_factor.cpp":19:42)
#loc103 = loc("cfd_step_factor.cpp":19:71)
#loc104 = loc("cfd_step_factor.cpp":19:70)
#loc105 = loc("cfd_step_factor.cpp":19:79)
#loc106 = loc("cfd_step_factor.cpp":19:78)
#loc107 = loc("cfd_step_factor.cpp":19:57)
#loc108 = loc("cfd_step_factor.cpp":19:40)
#loc109 = loc("cfd_step_factor.cpp":20:1)
#loc111 = loc("./cfd_step_factor.h":21:15)
#loc112 = loc("cfd_step_factor.cpp":22:1)
#loc113 = loc("cfd_step_factor.cpp":24:30)
#loc114 = loc("cfd_step_factor.cpp":24:29)
#loc115 = loc("cfd_step_factor.cpp":24:41)
#loc116 = loc("cfd_step_factor.cpp":24:39)
#loc117 = loc("cfd_step_factor.cpp":24:12)
#loc118 = loc("cfd_step_factor.cpp":25:1)
#loc120 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":462:3)
#loc121 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:8)
#loc122 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":464:12)
#loc123 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":464:34)
