#loc1 = loc("cfd_step_factor.cpp":48:6)
#loc5 = loc("./cfd_step_factor.h":14:20)
#loc6 = loc("cfd_step_factor.cpp":66:33)
#loc45 = loc("cfd_step_factor.cpp":27:6)
#loc105 = loc("cfd_step_factor.cpp":5:13)
#loc126 = loc("cfd_step_factor.cpp":12:14)
#loc140 = loc("cfd_step_factor.cpp":17:14)
#loc152 = loc("cfd_step_factor.cpp":22:14)
#loc161 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:3)
module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<!llvm.ptr<271>, dense<32> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi32>>, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr<270>, dense<32> : vector<4xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr, dense<64> : vector<4xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<"dlti.endianness", "little">, #dlti.dl_entry<"dlti.stack_alignment", 128 : i32>>, llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu", "polygeist.target-cpu" = "x86-64", "polygeist.target-features" = "+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87", "polygeist.tune-cpu" = "generic"} {
  func.func @workload(%arg0: memref<1024xf32> loc("cfd_step_factor.cpp":48:6), %arg1: memref<5120xf32> loc("cfd_step_factor.cpp":48:6), %arg2: memref<1024xf32> loc("cfd_step_factor.cpp":48:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %c5_i64 = arith.constant 5 : i64 loc(#loc2)
    %c1024_i64 = arith.constant 1024 : i64 loc(#loc3)
    %c5_i32 = arith.constant 5 : i32 loc(#loc4)
    %c1024_i32 = arith.constant 1024 : i32 loc(#loc5)
    %c1_i32 = arith.constant 1 : i32 loc(#loc6)
    %c0_i32 = arith.constant 0 : i32 loc(#loc7)
    %true = arith.constant true loc(#loc8)
    %0 = "polygeist.undef"() : () -> i32 loc(#loc9)
    %alloca = memref.alloca() : memref<1024xf32> loc(#loc10)
    %alloca_0 = memref.alloca() : memref<5120xf32> loc(#loc11)
    %alloca_1 = memref.alloca() : memref<1024xf32> loc(#loc12)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc13)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc14)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc15)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc16)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            %1 = scf.if %true -> (i32) {
              %3 = scf.execute_region -> i32 {
                scf.yield %c0_i32 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %3 : i32 loc(#loc)
            } else {
              scf.yield %0 : i32 loc(#loc)
            } loc(#loc)
            %2 = scf.while (%arg3 = %1) : (i32) -> i32 {
              %3 = arith.cmpi slt, %arg3, %c1_i32 : i32 loc(#loc17)
              scf.condition(%3) %arg3 : i32 loc(#loc18)
            } do {
            ^bb0(%arg3: i32 loc("cfd_step_factor.cpp":66:33)):
              scf.if %true {
                scf.execute_region {
                  %4 = "polygeist.memref2pointer"(%alloca_0) : (memref<5120xf32>) -> !llvm.ptr loc(#loc19)
                  %5 = arith.muli %arg3, %c1024_i32 : i32 loc(#loc20)
                  %6 = arith.muli %5, %c5_i32 : i32 loc(#loc21)
                  %7 = arith.index_cast %6 : i32 to index loc(#loc22)
                  %8 = "polygeist.subindex"(%arg1, %7) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc22)
                  %9 = "polygeist.memref2pointer"(%8) : (memref<?xf32>) -> !llvm.ptr loc(#loc23)
                  %10 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc24)
                  %11 = arith.index_cast %10 : index to i64 loc(#loc24)
                  %12 = arith.muli %11, %c1024_i64 : i64 loc(#loc25)
                  %13 = arith.muli %12, %c5_i64 : i64 loc(#loc26)
                  "llvm.intr.memcpy"(%4, %9, %13) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc27)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %4 = "polygeist.memref2pointer"(%alloca) : (memref<1024xf32>) -> !llvm.ptr loc(#loc28)
                  %5 = arith.muli %arg3, %c1024_i32 : i32 loc(#loc29)
                  %6 = arith.index_cast %5 : i32 to index loc(#loc30)
                  %7 = "polygeist.subindex"(%arg2, %6) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc30)
                  %8 = "polygeist.memref2pointer"(%7) : (memref<?xf32>) -> !llvm.ptr loc(#loc31)
                  %9 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc32)
                  %10 = arith.index_cast %9 : index to i64 loc(#loc32)
                  %11 = arith.muli %10, %c1024_i64 : i64 loc(#loc33)
                  "llvm.intr.memcpy"(%4, %8, %11) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc34)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  func.call @cfd_step_factor(%alloca_1, %alloca_0, %alloca) : (memref<1024xf32>, memref<5120xf32>, memref<1024xf32>) -> () loc(#loc35)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %4 = arith.muli %arg3, %c1024_i32 : i32 loc(#loc36)
                  %5 = arith.index_cast %4 : i32 to index loc(#loc37)
                  %6 = "polygeist.subindex"(%arg0, %5) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc37)
                  %7 = "polygeist.memref2pointer"(%6) : (memref<?xf32>) -> !llvm.ptr loc(#loc38)
                  %8 = "polygeist.memref2pointer"(%alloca_1) : (memref<1024xf32>) -> !llvm.ptr loc(#loc39)
                  %9 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc40)
                  %10 = arith.index_cast %9 : index to i64 loc(#loc40)
                  %11 = arith.muli %10, %c1024_i64 : i64 loc(#loc41)
                  "llvm.intr.memcpy"(%7, %8, %11) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc42)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              %3 = scf.if %true -> (i32) {
                %4 = scf.execute_region -> i32 {
                  %5 = arith.addi %arg3, %c1_i32 : i32 loc(#loc43)
                  scf.yield %5 : i32 loc(#loc)
                } loc(#loc)
                scf.yield %4 : i32 loc(#loc)
              } else {
                scf.yield %arg3 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %3 : i32 loc(#loc18)
            } loc(#loc6)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc44)
  } loc(#loc1)
  func.func @cfd_step_factor(%arg0: memref<1024xf32> loc("cfd_step_factor.cpp":27:6), %arg1: memref<5120xf32> loc("cfd_step_factor.cpp":27:6), %arg2: memref<1024xf32> loc("cfd_step_factor.cpp":27:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %cst = arith.constant 5.000000e-01 : f32 loc(#loc46)
    %c4_i32 = arith.constant 4 : i32 loc(#loc47)
    %c3_i32 = arith.constant 3 : i32 loc(#loc48)
    %c2_i32 = arith.constant 2 : i32 loc(#loc49)
    %c1_i32 = arith.constant 1 : i32 loc(#loc50)
    %c5_i32 = arith.constant 5 : i32 loc(#loc4)
    %c1024_i32 = arith.constant 1024 : i32 loc(#loc5)
    %c0_i32 = arith.constant 0 : i32 loc(#loc51)
    %true = arith.constant true loc(#loc52)
    %c1 = arith.constant 1 : index loc(#loc)
    %c2 = arith.constant 2 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc53)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc53)
    %alloca = memref.alloca() : memref<1xf32> loc(#loc54)
    %cast = memref.cast %alloca : memref<1xf32> to memref<?xf32> loc(#loc54)
    affine.store %0, %alloca[0] : memref<1xf32> loc(#loc54)
    %alloca_0 = memref.alloca() : memref<1xf32> loc(#loc55)
    %cast_1 = memref.cast %alloca_0 : memref<1xf32> to memref<?xf32> loc(#loc55)
    affine.store %0, %alloca_0[0] : memref<1xf32> loc(#loc55)
    %alloca_2 = memref.alloca() : memref<1x3xf32> loc(#loc56)
    %cast_3 = memref.cast %alloca_2 : memref<1x3xf32> to memref<?x3xf32> loc(#loc56)
    %alloca_4 = memref.alloca() : memref<1xf32> loc(#loc57)
    %cast_5 = memref.cast %alloca_4 : memref<1xf32> to memref<?xf32> loc(#loc57)
    affine.store %0, %alloca_4[0] : memref<1xf32> loc(#loc57)
    %alloca_6 = memref.alloca() : memref<1x3xf32> loc(#loc58)
    %cast_7 = memref.cast %alloca_6 : memref<1x3xf32> to memref<?x3xf32> loc(#loc58)
    %alloca_8 = memref.alloca() : memref<1xf32> loc(#loc59)
    %cast_9 = memref.cast %alloca_8 : memref<1xf32> to memref<?xf32> loc(#loc59)
    affine.store %0, %alloca_8[0] : memref<1xf32> loc(#loc59)
    %1 = "polygeist.undef"() : () -> i32 loc(#loc60)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc61)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            %2 = scf.if %true -> (i32) {
              %4 = scf.execute_region -> i32 {
                scf.yield %c0_i32 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %4 : i32 loc(#loc)
            } else {
              scf.yield %1 : i32 loc(#loc)
            } loc(#loc)
            %3:2 = scf.while (%arg3 = %0, %arg4 = %2) : (f32, i32) -> (f32, i32) {
              %4 = arith.cmpi slt, %arg4, %c1024_i32 : i32 loc(#loc62)
              scf.condition(%4) %arg3, %arg4 : f32, i32 loc(#loc63)
            } do {
            ^bb0(%arg3: f32 loc("./cfd_step_factor.h":14:20), %arg4: i32 loc("./cfd_step_factor.h":14:20)):
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = arith.muli %arg4, %c5_i32 : i32 loc(#loc64)
                      %7 = arith.index_cast %6 : i32 to index loc(#loc65)
                      %8 = "polygeist.subindex"(%arg1, %7) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc66)
                      %9 = affine.load %8[0] : memref<?xf32> loc(#loc66)
                      affine.store %9, %alloca_8[0] : memref<1xf32> loc(#loc59)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc67)
                  %7 = "polygeist.subindex"(%6, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc67)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc68)
                  %9 = arith.addi %8, %c1_i32 : i32 loc(#loc69)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc70)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc71)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc71)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc72)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc73)
                  %7 = "polygeist.subindex"(%6, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc73)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc74)
                  %9 = arith.addi %8, %c2_i32 : i32 loc(#loc75)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc76)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc77)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc77)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc78)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = "polygeist.subindex"(%alloca_6, %c0) : (memref<1x3xf32>, index) -> memref<3xf32> loc(#loc79)
                  %7 = "polygeist.subindex"(%6, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc79)
                  %8 = arith.muli %arg4, %c5_i32 : i32 loc(#loc80)
                  %9 = arith.addi %8, %c3_i32 : i32 loc(#loc81)
                  %10 = arith.index_cast %9 : i32 to index loc(#loc82)
                  %11 = "polygeist.subindex"(%arg1, %10) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc83)
                  %12 = affine.load %11[0] : memref<?xf32> loc(#loc83)
                  affine.store %12, %7[0] : memref<?xf32> loc(#loc84)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = arith.muli %arg4, %c5_i32 : i32 loc(#loc85)
                      %7 = arith.addi %6, %c4_i32 : i32 loc(#loc86)
                      %8 = arith.index_cast %7 : i32 to index loc(#loc87)
                      %9 = "polygeist.subindex"(%arg1, %8) : (memref<5120xf32>, index) -> memref<?xf32> loc(#loc88)
                      %10 = affine.load %9[0] : memref<?xf32> loc(#loc88)
                      affine.store %10, %alloca_4[0] : memref<1xf32> loc(#loc57)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  func.call @compute_velocity(%cast_9, %cast_7, %cast_3) : (memref<?xf32>, memref<?x3xf32>, memref<?x3xf32>) -> () loc(#loc89)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = func.call @compute_speed_sqd(%cast_3) : (memref<?x3xf32>) -> f32 loc(#loc90)
                      affine.store %6, %alloca_0[0] : memref<1xf32> loc(#loc55)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %6 = func.call @compute_pressure(%cast_9, %cast_5, %cast_1) : (memref<?xf32>, memref<?xf32>, memref<?xf32>) -> f32 loc(#loc91)
                      affine.store %6, %alloca[0] : memref<1xf32> loc(#loc54)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              %4 = scf.if %true -> (f32) {
                %6 = scf.execute_region -> f32 {
                  %7 = scf.if %true -> (f32) {
                    %8 = scf.execute_region -> f32 {
                      %9 = func.call @compute_speed_of_sound(%cast_9, %cast) : (memref<?xf32>, memref<?xf32>) -> f32 loc(#loc92)
                      scf.yield %9 : f32 loc(#loc)
                    } loc(#loc)
                    scf.yield %8 : f32 loc(#loc)
                  } else {
                    scf.yield %arg3 : f32 loc(#loc)
                  } loc(#loc)
                  scf.yield %7 : f32 loc(#loc)
                } loc(#loc)
                scf.yield %6 : f32 loc(#loc)
              } else {
                scf.yield %arg3 : f32 loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %6 = arith.index_cast %arg4 : i32 to index loc(#loc93)
                  %7 = "polygeist.subindex"(%arg0, %6) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc94)
                  %8 = "polygeist.subindex"(%arg2, %6) : (memref<1024xf32>, index) -> memref<?xf32> loc(#loc95)
                  %9 = affine.load %8[0] : memref<?xf32> loc(#loc95)
                  %10 = func.call @_ZSt4sqrtf(%9) : (f32) -> f32 loc(#loc96)
                  %11 = affine.load %alloca_0[0] : memref<1xf32> loc(#loc97)
                  %12 = func.call @_ZSt4sqrtf(%11) : (f32) -> f32 loc(#loc98)
                  %13 = arith.addf %12, %4 : f32 loc(#loc99)
                  %14 = arith.mulf %10, %13 : f32 loc(#loc100)
                  %15 = arith.divf %cst, %14 : f32 loc(#loc101)
                  affine.store %15, %7[0] : memref<?xf32> loc(#loc102)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              %5 = scf.if %true -> (i32) {
                %6 = scf.execute_region -> i32 {
                  %7 = arith.addi %arg4, %c1_i32 : i32 loc(#loc103)
                  scf.yield %7 : i32 loc(#loc)
                } loc(#loc)
                scf.yield %6 : i32 loc(#loc)
              } else {
                scf.yield %arg4 : i32 loc(#loc)
              } loc(#loc)
              scf.yield %4, %5 : f32, i32 loc(#loc63)
            } loc(#loc5)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc104)
  } loc(#loc45)
  func.func @compute_velocity(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":5:13), %arg1: memref<?x3xf32> loc("cfd_step_factor.cpp":5:13), %arg2: memref<?x3xf32> loc("cfd_step_factor.cpp":5:13)) attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %c2 = arith.constant 2 : index loc(#loc)
    %c1 = arith.constant 1 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc106)
    %true = arith.constant true loc(#loc107)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc108)
        %1 = "polygeist.subindex"(%0, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc108)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc109)
        %3 = "polygeist.subindex"(%2, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc109)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc106)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc110)
        %6 = arith.divf %4, %5 : f32 loc(#loc111)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc112)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc113)
        %1 = "polygeist.subindex"(%0, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc113)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc114)
        %3 = "polygeist.subindex"(%2, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc114)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc115)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc116)
        %6 = arith.divf %4, %5 : f32 loc(#loc117)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc118)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %0 = "polygeist.subindex"(%arg2, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc119)
        %1 = "polygeist.subindex"(%0, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc119)
        %2 = "polygeist.subindex"(%arg1, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc120)
        %3 = "polygeist.subindex"(%2, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc120)
        %4 = affine.load %3[0] : memref<?xf32> loc(#loc121)
        %5 = affine.load %arg0[0] : memref<?xf32> loc(#loc122)
        %6 = arith.divf %4, %5 : f32 loc(#loc123)
        affine.store %6, %1[0] : memref<?xf32> loc(#loc124)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc125)
  } loc(#loc105)
  func.func @compute_speed_sqd(%arg0: memref<?x3xf32> loc("cfd_step_factor.cpp":12:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %c2 = arith.constant 2 : index loc(#loc)
    %c1 = arith.constant 1 : index loc(#loc)
    %c0 = arith.constant 0 : index loc(#loc127)
    %true = arith.constant true loc(#loc128)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc128)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = "polygeist.subindex"(%arg0, %c0) : (memref<?x3xf32>, index) -> memref<3xf32> loc(#loc129)
            %6 = "polygeist.subindex"(%5, %c0) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc129)
            %7 = affine.load %6[0] : memref<?xf32> loc(#loc127)
            %8 = arith.mulf %7, %7 : f32 loc(#loc130)
            %9 = "polygeist.subindex"(%5, %c1) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc131)
            %10 = affine.load %9[0] : memref<?xf32> loc(#loc132)
            %11 = arith.mulf %10, %10 : f32 loc(#loc133)
            %12 = arith.addf %8, %11 : f32 loc(#loc134)
            %13 = "polygeist.subindex"(%5, %c2) : (memref<3xf32>, index) -> memref<?xf32> loc(#loc135)
            %14 = affine.load %13[0] : memref<?xf32> loc(#loc136)
            %15 = arith.mulf %14, %14 : f32 loc(#loc137)
            %16 = arith.addf %12, %15 : f32 loc(#loc138)
            scf.yield %16 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc139)
  } loc(#loc126)
  func.func @compute_pressure(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":17:14), %arg1: memref<?xf32> loc("cfd_step_factor.cpp":17:14), %arg2: memref<?xf32> loc("cfd_step_factor.cpp":17:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %cst = arith.constant 5.000000e-01 : f32 loc(#loc141)
    %cst_0 = arith.constant 0.399999976 : f32 loc(#loc142)
    %true = arith.constant true loc(#loc143)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc143)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = affine.load %arg1[0] : memref<?xf32> loc(#loc144)
            %6 = affine.load %arg0[0] : memref<?xf32> loc(#loc145)
            %7 = arith.mulf %6, %cst : f32 loc(#loc146)
            %8 = affine.load %arg2[0] : memref<?xf32> loc(#loc147)
            %9 = arith.mulf %7, %8 : f32 loc(#loc148)
            %10 = arith.subf %5, %9 : f32 loc(#loc149)
            %11 = arith.mulf %10, %cst_0 : f32 loc(#loc150)
            scf.yield %11 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc151)
  } loc(#loc140)
  func.func @compute_speed_of_sound(%arg0: memref<?xf32> loc("cfd_step_factor.cpp":22:14), %arg1: memref<?xf32> loc("cfd_step_factor.cpp":22:14)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %cst = arith.constant 1.400000e+00 : f32 loc(#loc153)
    %true = arith.constant true loc(#loc154)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc154)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = affine.load %arg1[0] : memref<?xf32> loc(#loc155)
            %6 = arith.mulf %5, %cst : f32 loc(#loc156)
            %7 = affine.load %arg0[0] : memref<?xf32> loc(#loc157)
            %8 = arith.divf %6, %7 : f32 loc(#loc158)
            %9 = func.call @_ZSt4sqrtf(%8) : (f32) -> f32 loc(#loc159)
            scf.yield %9 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc160)
  } loc(#loc152)
  func.func @_ZSt4sqrtf(%arg0: f32 loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:3)) -> f32 attributes {llvm.linkage = #llvm.linkage<linkonce_odr>} {
    %true = arith.constant true loc(#loc162)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc163)
    %1 = scf.if %true -> (f32) {
      %2 = scf.execute_region -> f32 {
        %3 = scf.if %true -> (f32) {
          %4 = scf.execute_region -> f32 {
            %5 = math.sqrt %arg0 : f32 loc(#loc164)
            scf.yield %5 : f32 loc(#loc)
          } loc(#loc)
          scf.yield %4 : f32 loc(#loc)
        } else {
          scf.yield %0 : f32 loc(#loc)
        } loc(#loc)
        scf.yield %3 : f32 loc(#loc)
      } loc(#loc)
      scf.yield %2 : f32 loc(#loc)
    } else {
      scf.yield %0 : f32 loc(#loc)
    } loc(#loc)
    return %1 : f32 loc(#loc165)
  } loc(#loc161)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("./cfd_step_factor.h":33:14)
#loc3 = loc("./cfd_step_factor.h":14:19)
#loc4 = loc("./cfd_step_factor.h":33:33)
#loc7 = loc("cfd_step_factor.cpp":66:21)
#loc8 = loc("cfd_step_factor.cpp":48:1)
#loc9 = loc("cfd_step_factor.cpp":66:13)
#loc10 = loc("cfd_step_factor.cpp":64:8)
#loc11 = loc("cfd_step_factor.cpp":63:8)
#loc12 = loc("cfd_step_factor.cpp":62:8)
#loc13 = loc("cfd_step_factor.cpp":62:1)
#loc14 = loc("cfd_step_factor.cpp":63:1)
#loc15 = loc("cfd_step_factor.cpp":64:1)
#loc16 = loc("cfd_step_factor.cpp":66:1)
#loc17 = loc("cfd_step_factor.cpp":66:26)
#loc18 = loc("cfd_step_factor.cpp":66:8)
#loc19 = loc("cfd_step_factor.cpp":68:16)
#loc20 = loc("cfd_step_factor.cpp":68:47)
#loc21 = loc("cfd_step_factor.cpp":68:59)
#loc22 = loc("cfd_step_factor.cpp":68:43)
#loc23 = loc("cfd_step_factor.cpp":68:33)
#loc24 = loc("cfd_step_factor.cpp":68:67)
#loc25 = loc("cfd_step_factor.cpp":68:81)
#loc26 = loc("cfd_step_factor.cpp":68:93)
#loc27 = loc("cfd_step_factor.cpp":68:9)
#loc28 = loc("cfd_step_factor.cpp":69:16)
#loc29 = loc("cfd_step_factor.cpp":69:39)
#loc30 = loc("cfd_step_factor.cpp":69:35)
#loc31 = loc("cfd_step_factor.cpp":69:29)
#loc32 = loc("cfd_step_factor.cpp":69:52)
#loc33 = loc("cfd_step_factor.cpp":69:66)
#loc34 = loc("cfd_step_factor.cpp":69:9)
#loc35 = loc("cfd_step_factor.cpp":71:9)
#loc36 = loc("cfd_step_factor.cpp":73:27)
#loc37 = loc("cfd_step_factor.cpp":73:23)
#loc38 = loc("cfd_step_factor.cpp":73:16)
#loc39 = loc("cfd_step_factor.cpp":73:40)
#loc40 = loc("cfd_step_factor.cpp":73:54)
#loc41 = loc("cfd_step_factor.cpp":73:68)
#loc42 = loc("cfd_step_factor.cpp":73:9)
#loc43 = loc("cfd_step_factor.cpp":66:47)
#loc44 = loc("cfd_step_factor.cpp":78:1)
#loc46 = loc("cfd_step_factor.cpp":44:24)
#loc47 = loc("./cfd_step_factor.h":32:41)
#loc48 = loc("cfd_step_factor.cpp":36:52)
#loc49 = loc("cfd_step_factor.cpp":35:52)
#loc50 = loc("cfd_step_factor.cpp":34:52)
#loc51 = loc("cfd_step_factor.cpp":29:21)
#loc52 = loc("cfd_step_factor.cpp":27:1)
#loc53 = loc("cfd_step_factor.cpp":42:6)
#loc54 = loc("cfd_step_factor.cpp":41:6)
#loc55 = loc("cfd_step_factor.cpp":40:6)
#loc56 = loc("cfd_step_factor.cpp":39:6)
#loc57 = loc("cfd_step_factor.cpp":38:6)
#loc58 = loc("cfd_step_factor.cpp":33:6)
#loc59 = loc("cfd_step_factor.cpp":31:6)
#loc60 = loc("cfd_step_factor.cpp":29:13)
#loc61 = loc("cfd_step_factor.cpp":29:1)
#loc62 = loc("cfd_step_factor.cpp":29:26)
#loc63 = loc("cfd_step_factor.cpp":29:8)
#loc64 = loc("cfd_step_factor.cpp":31:36)
#loc65 = loc("cfd_step_factor.cpp":31:52)
#loc66 = loc("cfd_step_factor.cpp":31:22)
#loc67 = loc("cfd_step_factor.cpp":34:15)
#loc68 = loc("cfd_step_factor.cpp":34:33)
#loc69 = loc("cfd_step_factor.cpp":34:36)
#loc70 = loc("cfd_step_factor.cpp":34:56)
#loc71 = loc("cfd_step_factor.cpp":34:19)
#loc72 = loc("cfd_step_factor.cpp":34:17)
#loc73 = loc("cfd_step_factor.cpp":35:15)
#loc74 = loc("cfd_step_factor.cpp":35:33)
#loc75 = loc("cfd_step_factor.cpp":35:36)
#loc76 = loc("cfd_step_factor.cpp":35:56)
#loc77 = loc("cfd_step_factor.cpp":35:19)
#loc78 = loc("cfd_step_factor.cpp":35:17)
#loc79 = loc("cfd_step_factor.cpp":36:15)
#loc80 = loc("cfd_step_factor.cpp":36:33)
#loc81 = loc("cfd_step_factor.cpp":36:36)
#loc82 = loc("cfd_step_factor.cpp":36:56)
#loc83 = loc("cfd_step_factor.cpp":36:19)
#loc84 = loc("cfd_step_factor.cpp":36:17)
#loc85 = loc("cfd_step_factor.cpp":38:43)
#loc86 = loc("cfd_step_factor.cpp":38:46)
#loc87 = loc("cfd_step_factor.cpp":38:66)
#loc88 = loc("cfd_step_factor.cpp":38:29)
#loc89 = loc("cfd_step_factor.cpp":39:29)
#loc90 = loc("cfd_step_factor.cpp":40:24)
#loc91 = loc("cfd_step_factor.cpp":41:23)
#loc92 = loc("cfd_step_factor.cpp":42:29)
#loc93 = loc("cfd_step_factor.cpp":44:14)
#loc94 = loc("cfd_step_factor.cpp":44:6)
#loc95 = loc("cfd_step_factor.cpp":44:38)
#loc96 = loc("cfd_step_factor.cpp":44:33)
#loc97 = loc("cfd_step_factor.cpp":44:56)
#loc98 = loc("cfd_step_factor.cpp":44:51)
#loc99 = loc("cfd_step_factor.cpp":44:67)
#loc100 = loc("cfd_step_factor.cpp":44:48)
#loc101 = loc("cfd_step_factor.cpp":44:30)
#loc102 = loc("cfd_step_factor.cpp":44:16)
#loc103 = loc("cfd_step_factor.cpp":29:40)
#loc104 = loc("cfd_step_factor.cpp":46:1)
#loc106 = loc("cfd_step_factor.cpp":7:18)
#loc107 = loc("cfd_step_factor.cpp":5:1)
#loc108 = loc("cfd_step_factor.cpp":7:14)
#loc109 = loc("cfd_step_factor.cpp":7:27)
#loc110 = loc("cfd_step_factor.cpp":7:31)
#loc111 = loc("cfd_step_factor.cpp":7:29)
#loc112 = loc("cfd_step_factor.cpp":7:16)
#loc113 = loc("cfd_step_factor.cpp":8:14)
#loc114 = loc("cfd_step_factor.cpp":8:27)
#loc115 = loc("cfd_step_factor.cpp":8:18)
#loc116 = loc("cfd_step_factor.cpp":8:31)
#loc117 = loc("cfd_step_factor.cpp":8:29)
#loc118 = loc("cfd_step_factor.cpp":8:16)
#loc119 = loc("cfd_step_factor.cpp":9:14)
#loc120 = loc("cfd_step_factor.cpp":9:27)
#loc121 = loc("cfd_step_factor.cpp":9:18)
#loc122 = loc("cfd_step_factor.cpp":9:31)
#loc123 = loc("cfd_step_factor.cpp":9:29)
#loc124 = loc("cfd_step_factor.cpp":9:16)
#loc125 = loc("cfd_step_factor.cpp":10:1)
#loc127 = loc("cfd_step_factor.cpp":14:12)
#loc128 = loc("cfd_step_factor.cpp":12:1)
#loc129 = loc("cfd_step_factor.cpp":14:21)
#loc130 = loc("cfd_step_factor.cpp":14:22)
#loc131 = loc("cfd_step_factor.cpp":14:45)
#loc132 = loc("cfd_step_factor.cpp":14:36)
#loc133 = loc("cfd_step_factor.cpp":14:46)
#loc134 = loc("cfd_step_factor.cpp":14:34)
#loc135 = loc("cfd_step_factor.cpp":14:69)
#loc136 = loc("cfd_step_factor.cpp":14:60)
#loc137 = loc("cfd_step_factor.cpp":14:70)
#loc138 = loc("cfd_step_factor.cpp":14:58)
#loc139 = loc("cfd_step_factor.cpp":15:1)
#loc141 = loc("cfd_step_factor.cpp":19:65)
#loc142 = loc("cfd_step_factor.cpp":19:26)
#loc143 = loc("cfd_step_factor.cpp":17:1)
#loc144 = loc("cfd_step_factor.cpp":19:42)
#loc145 = loc("cfd_step_factor.cpp":19:71)
#loc146 = loc("cfd_step_factor.cpp":19:70)
#loc147 = loc("cfd_step_factor.cpp":19:79)
#loc148 = loc("cfd_step_factor.cpp":19:78)
#loc149 = loc("cfd_step_factor.cpp":19:57)
#loc150 = loc("cfd_step_factor.cpp":19:40)
#loc151 = loc("cfd_step_factor.cpp":20:1)
#loc153 = loc("./cfd_step_factor.h":21:15)
#loc154 = loc("cfd_step_factor.cpp":22:1)
#loc155 = loc("cfd_step_factor.cpp":24:30)
#loc156 = loc("cfd_step_factor.cpp":24:29)
#loc157 = loc("cfd_step_factor.cpp":24:41)
#loc158 = loc("cfd_step_factor.cpp":24:39)
#loc159 = loc("cfd_step_factor.cpp":24:12)
#loc160 = loc("cfd_step_factor.cpp":25:1)
#loc162 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":462:3)
#loc163 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":463:8)
#loc164 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":464:12)
#loc165 = loc("/usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/cmath":464:34)
