#loc1 = loc("streamcluster.cpp":51:6)
#loc156 = loc("streamcluster.cpp":6:6)
#loc200 = loc("streamcluster.cpp":17:6)
#loc297 = loc("streamcluster.cpp":44:6)
module attributes {dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<f80, dense<128> : vector<2xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr, dense<64> : vector<4xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr<270>, dense<32> : vector<4xi32>>, #dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi32>>, #dlti.dl_entry<!llvm.ptr<271>, dense<32> : vector<4xi32>>, #dlti.dl_entry<i64, dense<64> : vector<2xi32>>, #dlti.dl_entry<"dlti.stack_alignment", 128 : i32>, #dlti.dl_entry<"dlti.endianness", "little">>, llvm.data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", llvm.target_triple = "x86_64-unknown-linux-gnu", "polygeist.target-cpu" = "x86-64", "polygeist.target-features" = "+cmov,+cx8,+fxsr,+mmx,+sse,+sse2,+x87", "polygeist.tune-cpu" = "generic"} {
  func.func @workload(%arg0: memref<?xf32> loc("streamcluster.cpp":51:6), %arg1: memref<?xf32> loc("streamcluster.cpp":51:6), %arg2: memref<?xf32> loc("streamcluster.cpp":51:6), %arg3: memref<?xf32> loc("streamcluster.cpp":51:6), %arg4: memref<?xi32> loc("streamcluster.cpp":51:6), %arg5: memref<?xi32> loc("streamcluster.cpp":51:6), %arg6: memref<?xi8> loc("streamcluster.cpp":51:6), %arg7: memref<?xf32> loc("streamcluster.cpp":51:6), %arg8: i32 loc("streamcluster.cpp":51:6), %arg9: memref<?xf32> loc("streamcluster.cpp":51:6), %arg10: i32 loc("streamcluster.cpp":51:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %c-256_i32 = arith.constant -256 : i32 loc(#loc2)
    %c2_i32 = arith.constant 2 : i32 loc(#loc3)
    %c256_i32 = arith.constant 256 : i32 loc(#loc2)
    %c1024_i32 = arith.constant 1024 : i32 loc(#loc4)
    %false = arith.constant false loc(#loc)
    %c1280_i32 = arith.constant 1280 : i32 loc(#loc5)
    %c0_i32 = arith.constant 0 : i32 loc(#loc6)
    %c200_i64 = arith.constant 200 : i64 loc(#loc7)
    %c1024_i64 = arith.constant 1024 : i64 loc(#loc4)
    %true = arith.constant true loc(#loc8)
    %alloca = memref.alloca() : memref<1xi32> loc(#loc9)
    %0 = "polygeist.undef"() : () -> i32 loc(#loc9)
    affine.store %0, %alloca[0] : memref<1xi32> loc(#loc9)
    %alloca_0 = memref.alloca() : memref<1xi32> loc(#loc10)
    affine.store %0, %alloca_0[0] : memref<1xi32> loc(#loc10)
    %alloca_1 = memref.alloca() : memref<1xi32> loc(#loc11)
    affine.store %0, %alloca_1[0] : memref<1xi32> loc(#loc11)
    %alloca_2 = memref.alloca() : memref<51200xf32> loc(#loc12)
    %alloca_3 = memref.alloca() : memref<256xf32> loc(#loc13)
    %alloca_4 = memref.alloca() : memref<256xf32> loc(#loc14)
    %alloca_5 = memref.alloca() : memref<256xi32> loc(#loc15)
    %alloca_6 = memref.alloca() : memref<51200xf32> loc(#loc16)
    %alloca_7 = memref.alloca() : memref<256xf32> loc(#loc17)
    %alloca_8 = memref.alloca() : memref<256xf32> loc(#loc18)
    %alloca_9 = memref.alloca() : memref<256xi32> loc(#loc19)
    %alloca_10 = memref.alloca() : memref<256xf32> loc(#loc20)
    %alloca_11 = memref.alloca() : memref<1xf32> loc(#loc21)
    %alloca_12 = memref.alloca() : memref<1024xi8> loc(#loc22)
    %alloca_13 = memref.alloca() : memref<1024xf32> loc(#loc23)
    %alloca_14 = memref.alloca() : memref<1024xi32> loc(#loc24)
    %alloca_15 = memref.alloca() : memref<200xf32> loc(#loc25)
    %alloca_16 = memref.alloca() : memref<1xi32> loc(#loc26)
    affine.store %0, %alloca_16[0] : memref<1xi32> loc(#loc26)
    %alloca_17 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc27)
    %alloca_18 = memref.alloca() : memref<1xi32> loc(#loc28)
    affine.store %0, %alloca_18[0] : memref<1xi32> loc(#loc28)
    %alloca_19 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc29)
    %alloca_20 = memref.alloca() : memref<1xmemref<?xi8>> loc(#loc30)
    %alloca_21 = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc31)
    %alloca_22 = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc32)
    %alloca_23 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc33)
    %alloca_24 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc34)
    %alloca_25 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc35)
    %alloca_26 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc36)
    affine.store %arg0, %alloca_26[0] : memref<1xmemref<?xf32>> loc(#loc36)
    affine.store %arg1, %alloca_25[0] : memref<1xmemref<?xf32>> loc(#loc35)
    affine.store %arg2, %alloca_24[0] : memref<1xmemref<?xf32>> loc(#loc34)
    affine.store %arg3, %alloca_23[0] : memref<1xmemref<?xf32>> loc(#loc33)
    affine.store %arg4, %alloca_22[0] : memref<1xmemref<?xi32>> loc(#loc32)
    affine.store %arg5, %alloca_21[0] : memref<1xmemref<?xi32>> loc(#loc31)
    affine.store %arg6, %alloca_20[0] : memref<1xmemref<?xi8>> loc(#loc30)
    affine.store %arg7, %alloca_19[0] : memref<1xmemref<?xf32>> loc(#loc29)
    affine.store %arg8, %alloca_18[0] : memref<1xi32> loc(#loc28)
    affine.store %arg9, %alloca_17[0] : memref<1xmemref<?xf32>> loc(#loc27)
    affine.store %arg10, %alloca_16[0] : memref<1xi32> loc(#loc26)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc37)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc38)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc39)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc40)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc41)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = affine.load %alloca_17[0] : memref<1xmemref<?xf32>> loc(#loc42)
        %2 = affine.load %1[0] : memref<?xf32> loc(#loc42)
        affine.store %2, %alloca_11[0] : memref<1xf32> loc(#loc43)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc44)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc45)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc46)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc47)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc48)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc49)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc50)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc51)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc52)
      ^bb1:  // pred: ^bb0
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = "polygeist.memref2pointer"(%alloca_13) : (memref<1024xf32>) -> !llvm.ptr loc(#loc53)
        %2 = affine.load %alloca_19[0] : memref<1xmemref<?xf32>> loc(#loc54)
        %3 = "polygeist.memref2pointer"(%2) : (memref<?xf32>) -> !llvm.ptr loc(#loc54)
        %4 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc55)
        %5 = arith.index_cast %4 : index to i64 loc(#loc55)
        %6 = arith.muli %5, %c1024_i64 : i64 loc(#loc56)
        "llvm.intr.memcpy"(%1, %3, %6) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc57)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = "polygeist.memref2pointer"(%alloca_12) : (memref<1024xi8>) -> !llvm.ptr loc(#loc58)
        %2 = affine.load %alloca_20[0] : memref<1xmemref<?xi8>> loc(#loc59)
        %3 = "polygeist.memref2pointer"(%2) : (memref<?xi8>) -> !llvm.ptr loc(#loc59)
        %4 = "polygeist.typeSize"() <{source = i8}> : () -> index loc(#loc60)
        %5 = arith.index_cast %4 : index to i64 loc(#loc60)
        %6 = arith.muli %5, %c1024_i64 : i64 loc(#loc61)
        "llvm.intr.memcpy"(%1, %3, %6) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc62)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = "polygeist.memref2pointer"(%alloca_15) : (memref<200xf32>) -> !llvm.ptr loc(#loc63)
        %2 = affine.load %alloca_23[0] : memref<1xmemref<?xf32>> loc(#loc64)
        %3 = "polygeist.memref2pointer"(%2) : (memref<?xf32>) -> !llvm.ptr loc(#loc64)
        %4 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc65)
        %5 = arith.index_cast %4 : index to i64 loc(#loc65)
        %6 = arith.muli %5, %c200_i64 : i64 loc(#loc66)
        "llvm.intr.memcpy"(%1, %3, %6) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc67)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = "polygeist.memref2pointer"(%alloca_14) : (memref<1024xi32>) -> !llvm.ptr loc(#loc68)
        %2 = affine.load %alloca_21[0] : memref<1xmemref<?xi32>> loc(#loc69)
        %3 = "polygeist.memref2pointer"(%2) : (memref<?xi32>) -> !llvm.ptr loc(#loc69)
        %4 = "polygeist.typeSize"() <{source = i32}> : () -> index loc(#loc70)
        %5 = arith.index_cast %4 : index to i64 loc(#loc70)
        %6 = arith.muli %5, %c1024_i64 : i64 loc(#loc71)
        "llvm.intr.memcpy"(%1, %3, %6) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc72)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        cf.br ^bb1 loc(#loc73)
      ^bb1:  // pred: ^bb0
        cf.br ^bb2 loc(#loc74)
      ^bb2:  // pred: ^bb1
        scf.if %true {
          scf.execute_region {
            scf.if %true {
              scf.execute_region {
                affine.store %c0_i32, %alloca_1[0] : memref<1xi32> loc(#loc11)
                scf.yield loc(#loc)
              } loc(#loc)
            } loc(#loc)
            scf.while : () -> () {
              %1 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc75)
              %2 = arith.cmpi slt, %1, %c1280_i32 : i32 loc(#loc76)
              scf.condition(%2) loc(#loc77)
            } do {
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %1 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc78)
                      %2 = arith.cmpi sge, %1, %c0_i32 : i32 loc(#loc79)
                      %3 = scf.if %2 -> (i1) {
                        %5 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc81)
                        %6 = arith.cmpi slt, %5, %c1024_i32 : i32 loc(#loc82)
                        scf.yield %6 : i1 loc(#loc80)
                      } else {
                        scf.yield %false : i1 loc(#loc80)
                      } loc(#loc80)
                      %4 = arith.extui %3 : i1 to i32 loc(#loc78)
                      affine.store %4, %alloca_0[0] : memref<1xi32> loc(#loc10)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %1 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc83)
                      %2 = arith.cmpi sge, %1, %c256_i32 : i32 loc(#loc84)
                      %3 = scf.if %2 -> (i1) {
                        %5 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc86)
                        %6 = arith.cmpi sle, %5, %c1280_i32 : i32 loc(#loc87)
                        scf.yield %6 : i1 loc(#loc85)
                      } else {
                        scf.yield %false : i1 loc(#loc85)
                      } loc(#loc85)
                      %4 = arith.extui %3 : i1 to i32 loc(#loc83)
                      affine.store %4, %alloca[0] : memref<1xi32> loc(#loc9)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  scf.if %true {
                    scf.execute_region {
                      %1 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc88)
                      %2 = arith.divsi %1, %c256_i32 : i32 loc(#loc89)
                      %3 = arith.remsi %2, %c2_i32 : i32 loc(#loc90)
                      %4 = arith.cmpi eq, %3, %c0_i32 : i32 loc(#loc91)
                      scf.if %4 {
                        scf.if %true {
                          scf.execute_region {
                            %5 = affine.load %alloca_0[0] : memref<1xi32> loc(#loc93)
                            %6 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc94)
                            %7 = affine.load %alloca_26[0] : memref<1xmemref<?xf32>> loc(#loc95)
                            %8 = affine.load %alloca_25[0] : memref<1xmemref<?xf32>> loc(#loc96)
                            %9 = affine.load %alloca_24[0] : memref<1xmemref<?xf32>> loc(#loc97)
                            %10 = affine.load %alloca_22[0] : memref<1xmemref<?xi32>> loc(#loc98)
                            %cast = memref.cast %alloca_6 : memref<51200xf32> to memref<?xf32> loc(#loc99)
                            %cast_27 = memref.cast %alloca_7 : memref<256xf32> to memref<?xf32> loc(#loc100)
                            %cast_28 = memref.cast %alloca_8 : memref<256xf32> to memref<?xf32> loc(#loc101)
                            %cast_29 = memref.cast %alloca_9 : memref<256xi32> to memref<?xi32> loc(#loc102)
                            func.call @load(%5, %6, %7, %8, %9, %10, %cast, %cast_27, %cast_28, %cast_29) : (i32, i32, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>) -> () loc(#loc103)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            %5 = affine.load %alloca[0] : memref<1xi32> loc(#loc104)
                            %6 = affine.load %alloca_18[0] : memref<1xi32> loc(#loc105)
                            %7 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc106)
                            %8 = arith.addi %7, %c-256_i32 : i32 loc(#loc107)
                            %cast = memref.cast %alloca_2 : memref<51200xf32> to memref<?xf32> loc(#loc108)
                            %cast_27 = memref.cast %alloca_3 : memref<256xf32> to memref<?xf32> loc(#loc109)
                            %cast_28 = memref.cast %alloca_15 : memref<200xf32> to memref<?xf32> loc(#loc110)
                            %cast_29 = memref.cast %alloca_4 : memref<256xf32> to memref<?xf32> loc(#loc111)
                            %cast_30 = memref.cast %alloca_5 : memref<256xi32> to memref<?xi32> loc(#loc112)
                            %cast_31 = memref.cast %alloca_14 : memref<1024xi32> to memref<?xi32> loc(#loc113)
                            %cast_32 = memref.cast %alloca_12 : memref<1024xi8> to memref<?xi8> loc(#loc114)
                            %cast_33 = memref.cast %alloca_11 : memref<1xf32> to memref<?xf32> loc(#loc115)
                            %cast_34 = memref.cast %alloca_13 : memref<1024xf32> to memref<?xf32> loc(#loc116)
                            %cast_35 = memref.cast %alloca_10 : memref<256xf32> to memref<?xf32> loc(#loc117)
                            func.call @compute(%5, %6, %8, %cast, %cast_27, %cast_28, %cast_29, %cast_30, %cast_31, %cast_32, %cast_33, %cast_34, %cast_35) : (i32, i32, i32, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>, memref<?xi32>, memref<?xi8>, memref<?xf32>, memref<?xf32>, memref<?xf32>) -> () loc(#loc118)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                      } else {
                        scf.if %true {
                          scf.execute_region {
                            %5 = affine.load %alloca_0[0] : memref<1xi32> loc(#loc119)
                            %6 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc120)
                            %7 = affine.load %alloca_26[0] : memref<1xmemref<?xf32>> loc(#loc121)
                            %8 = affine.load %alloca_25[0] : memref<1xmemref<?xf32>> loc(#loc122)
                            %9 = affine.load %alloca_24[0] : memref<1xmemref<?xf32>> loc(#loc123)
                            %10 = affine.load %alloca_22[0] : memref<1xmemref<?xi32>> loc(#loc124)
                            %cast = memref.cast %alloca_2 : memref<51200xf32> to memref<?xf32> loc(#loc125)
                            %cast_27 = memref.cast %alloca_3 : memref<256xf32> to memref<?xf32> loc(#loc126)
                            %cast_28 = memref.cast %alloca_4 : memref<256xf32> to memref<?xf32> loc(#loc127)
                            %cast_29 = memref.cast %alloca_5 : memref<256xi32> to memref<?xi32> loc(#loc128)
                            func.call @load(%5, %6, %7, %8, %9, %10, %cast, %cast_27, %cast_28, %cast_29) : (i32, i32, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>) -> () loc(#loc129)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            %5 = affine.load %alloca[0] : memref<1xi32> loc(#loc130)
                            %6 = affine.load %alloca_18[0] : memref<1xi32> loc(#loc131)
                            %7 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc132)
                            %8 = arith.addi %7, %c-256_i32 : i32 loc(#loc133)
                            %cast = memref.cast %alloca_6 : memref<51200xf32> to memref<?xf32> loc(#loc134)
                            %cast_27 = memref.cast %alloca_7 : memref<256xf32> to memref<?xf32> loc(#loc135)
                            %cast_28 = memref.cast %alloca_15 : memref<200xf32> to memref<?xf32> loc(#loc136)
                            %cast_29 = memref.cast %alloca_8 : memref<256xf32> to memref<?xf32> loc(#loc137)
                            %cast_30 = memref.cast %alloca_9 : memref<256xi32> to memref<?xi32> loc(#loc138)
                            %cast_31 = memref.cast %alloca_14 : memref<1024xi32> to memref<?xi32> loc(#loc139)
                            %cast_32 = memref.cast %alloca_12 : memref<1024xi8> to memref<?xi8> loc(#loc140)
                            %cast_33 = memref.cast %alloca_11 : memref<1xf32> to memref<?xf32> loc(#loc141)
                            %cast_34 = memref.cast %alloca_13 : memref<1024xf32> to memref<?xf32> loc(#loc142)
                            %cast_35 = memref.cast %alloca_10 : memref<256xf32> to memref<?xf32> loc(#loc143)
                            func.call @compute(%5, %6, %8, %cast, %cast_27, %cast_28, %cast_29, %cast_30, %cast_31, %cast_32, %cast_33, %cast_34, %cast_35) : (i32, i32, i32, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xf32>, memref<?xi32>, memref<?xi32>, memref<?xi8>, memref<?xf32>, memref<?xf32>, memref<?xf32>) -> () loc(#loc144)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                      } loc(#loc92)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %1 = affine.load %alloca_1[0] : memref<1xi32> loc(#loc145)
                  %2 = arith.addi %1, %c256_i32 : i32 loc(#loc145)
                  affine.store %2, %alloca_1[0] : memref<1xi32> loc(#loc145)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.yield loc(#loc77)
            } loc(#loc75)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = affine.load %alloca_18[0] : memref<1xi32> loc(#loc146)
        %2 = affine.load %alloca_16[0] : memref<1xi32> loc(#loc147)
        %3 = affine.load %alloca_19[0] : memref<1xmemref<?xf32>> loc(#loc148)
        %4 = affine.load %alloca_20[0] : memref<1xmemref<?xi8>> loc(#loc149)
        %5 = affine.load %alloca_17[0] : memref<1xmemref<?xf32>> loc(#loc150)
        %cast = memref.cast %alloca_13 : memref<1024xf32> to memref<?xf32> loc(#loc151)
        %cast_27 = memref.cast %alloca_12 : memref<1024xi8> to memref<?xi8> loc(#loc152)
        %cast_28 = memref.cast %alloca_11 : memref<1xf32> to memref<?xf32> loc(#loc153)
        func.call @store(%1, %2, %3, %4, %5, %cast, %cast_27, %cast_28) : (i32, i32, memref<?xf32>, memref<?xi8>, memref<?xf32>, memref<?xf32>, memref<?xi8>, memref<?xf32>) -> () loc(#loc154)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        scf.if %true {
          scf.execute_region {
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc155)
  } loc(#loc1)
  func.func @load(%arg0: i32 loc("streamcluster.cpp":6:6), %arg1: i32 loc("streamcluster.cpp":6:6), %arg2: memref<?xf32> loc("streamcluster.cpp":6:6), %arg3: memref<?xf32> loc("streamcluster.cpp":6:6), %arg4: memref<?xf32> loc("streamcluster.cpp":6:6), %arg5: memref<?xi32> loc("streamcluster.cpp":6:6), %arg6: memref<?xf32> loc("streamcluster.cpp":6:6), %arg7: memref<?xf32> loc("streamcluster.cpp":6:6), %arg8: memref<?xf32> loc("streamcluster.cpp":6:6), %arg9: memref<?xi32> loc("streamcluster.cpp":6:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %c51200_i64 = arith.constant 51200 : i64 loc(#loc2)
    %c256_i64 = arith.constant 256 : i64 loc(#loc2)
    %c200_i32 = arith.constant 200 : i32 loc(#loc7)
    %c0_i32 = arith.constant 0 : i32 loc(#loc157)
    %true = arith.constant true loc(#loc158)
    %alloca = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc159)
    %alloca_0 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc160)
    %alloca_1 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc161)
    %alloca_2 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc162)
    %alloca_3 = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc163)
    %alloca_4 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc164)
    %alloca_5 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc165)
    %alloca_6 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc166)
    %alloca_7 = memref.alloca() : memref<1xi32> loc(#loc167)
    %0 = "polygeist.undef"() : () -> i32 loc(#loc167)
    affine.store %0, %alloca_7[0] : memref<1xi32> loc(#loc167)
    %alloca_8 = memref.alloca() : memref<1xi32> loc(#loc168)
    affine.store %0, %alloca_8[0] : memref<1xi32> loc(#loc168)
    affine.store %arg0, %alloca_8[0] : memref<1xi32> loc(#loc168)
    affine.store %arg1, %alloca_7[0] : memref<1xi32> loc(#loc167)
    affine.store %arg2, %alloca_6[0] : memref<1xmemref<?xf32>> loc(#loc166)
    affine.store %arg3, %alloca_5[0] : memref<1xmemref<?xf32>> loc(#loc165)
    affine.store %arg4, %alloca_4[0] : memref<1xmemref<?xf32>> loc(#loc164)
    affine.store %arg5, %alloca_3[0] : memref<1xmemref<?xi32>> loc(#loc163)
    affine.store %arg6, %alloca_2[0] : memref<1xmemref<?xf32>> loc(#loc162)
    affine.store %arg7, %alloca_1[0] : memref<1xmemref<?xf32>> loc(#loc161)
    affine.store %arg8, %alloca_0[0] : memref<1xmemref<?xf32>> loc(#loc160)
    affine.store %arg9, %alloca[0] : memref<1xmemref<?xi32>> loc(#loc159)
    scf.if %true {
      scf.execute_region {
        scf.if %true {
          scf.execute_region {
            %1 = affine.load %alloca_8[0] : memref<1xi32> loc(#loc157)
            %2 = arith.cmpi ne, %1, %c0_i32 : i32 loc(#loc157)
            scf.if %2 {
              scf.if %true {
                scf.execute_region {
                  %3 = affine.load %alloca_2[0] : memref<1xmemref<?xf32>> loc(#loc170)
                  %4 = "polygeist.memref2pointer"(%3) : (memref<?xf32>) -> !llvm.ptr loc(#loc170)
                  %5 = affine.load %alloca_6[0] : memref<1xmemref<?xf32>> loc(#loc171)
                  %6 = affine.load %alloca_7[0] : memref<1xi32> loc(#loc172)
                  %7 = arith.muli %6, %c200_i32 : i32 loc(#loc173)
                  %8 = arith.index_cast %7 : i32 to index loc(#loc174)
                  %9 = "polygeist.subindex"(%5, %8) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc174)
                  %10 = "polygeist.memref2pointer"(%9) : (memref<?xf32>) -> !llvm.ptr loc(#loc171)
                  %11 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc175)
                  %12 = arith.index_cast %11 : index to i64 loc(#loc175)
                  %13 = arith.muli %12, %c51200_i64 : i64 loc(#loc176)
                  "llvm.intr.memcpy"(%4, %10, %13) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc177)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %3 = affine.load %alloca_1[0] : memref<1xmemref<?xf32>> loc(#loc178)
                  %4 = "polygeist.memref2pointer"(%3) : (memref<?xf32>) -> !llvm.ptr loc(#loc178)
                  %5 = affine.load %alloca_5[0] : memref<1xmemref<?xf32>> loc(#loc179)
                  %6 = affine.load %alloca_7[0] : memref<1xi32> loc(#loc180)
                  %7 = arith.index_cast %6 : i32 to index loc(#loc181)
                  %8 = "polygeist.subindex"(%5, %7) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc181)
                  %9 = "polygeist.memref2pointer"(%8) : (memref<?xf32>) -> !llvm.ptr loc(#loc179)
                  %10 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc182)
                  %11 = arith.index_cast %10 : index to i64 loc(#loc182)
                  %12 = arith.muli %11, %c256_i64 : i64 loc(#loc183)
                  "llvm.intr.memcpy"(%4, %9, %12) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc184)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %3 = affine.load %alloca_0[0] : memref<1xmemref<?xf32>> loc(#loc185)
                  %4 = "polygeist.memref2pointer"(%3) : (memref<?xf32>) -> !llvm.ptr loc(#loc185)
                  %5 = affine.load %alloca_4[0] : memref<1xmemref<?xf32>> loc(#loc186)
                  %6 = affine.load %alloca_7[0] : memref<1xi32> loc(#loc187)
                  %7 = arith.index_cast %6 : i32 to index loc(#loc188)
                  %8 = "polygeist.subindex"(%5, %7) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc188)
                  %9 = "polygeist.memref2pointer"(%8) : (memref<?xf32>) -> !llvm.ptr loc(#loc186)
                  %10 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc189)
                  %11 = arith.index_cast %10 : index to i64 loc(#loc189)
                  %12 = arith.muli %11, %c256_i64 : i64 loc(#loc190)
                  "llvm.intr.memcpy"(%4, %9, %12) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc191)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  %3 = affine.load %alloca[0] : memref<1xmemref<?xi32>> loc(#loc192)
                  %4 = "polygeist.memref2pointer"(%3) : (memref<?xi32>) -> !llvm.ptr loc(#loc192)
                  %5 = affine.load %alloca_3[0] : memref<1xmemref<?xi32>> loc(#loc193)
                  %6 = affine.load %alloca_7[0] : memref<1xi32> loc(#loc194)
                  %7 = arith.index_cast %6 : i32 to index loc(#loc195)
                  %8 = "polygeist.subindex"(%5, %7) : (memref<?xi32>, index) -> memref<?xi32> loc(#loc195)
                  %9 = "polygeist.memref2pointer"(%8) : (memref<?xi32>) -> !llvm.ptr loc(#loc193)
                  %10 = "polygeist.typeSize"() <{source = i32}> : () -> index loc(#loc196)
                  %11 = arith.index_cast %10 : index to i64 loc(#loc196)
                  %12 = arith.muli %11, %c256_i64 : i64 loc(#loc197)
                  "llvm.intr.memcpy"(%4, %9, %12) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc198)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
            } loc(#loc169)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc199)
  } loc(#loc156)
  func.func @compute(%arg0: i32 loc("streamcluster.cpp":17:6), %arg1: i32 loc("streamcluster.cpp":17:6), %arg2: i32 loc("streamcluster.cpp":17:6), %arg3: memref<?xf32> loc("streamcluster.cpp":17:6), %arg4: memref<?xf32> loc("streamcluster.cpp":17:6), %arg5: memref<?xf32> loc("streamcluster.cpp":17:6), %arg6: memref<?xf32> loc("streamcluster.cpp":17:6), %arg7: memref<?xi32> loc("streamcluster.cpp":17:6), %arg8: memref<?xi32> loc("streamcluster.cpp":17:6), %arg9: memref<?xi8> loc("streamcluster.cpp":17:6), %arg10: memref<?xf32> loc("streamcluster.cpp":17:6), %arg11: memref<?xf32> loc("streamcluster.cpp":17:6), %arg12: memref<?xf32> loc("streamcluster.cpp":17:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %c1_i8 = arith.constant 1 : i8 loc(#loc201)
    %c1_i32 = arith.constant 1 : i32 loc(#loc202)
    %c200_i32 = arith.constant 200 : i32 loc(#loc7)
    %cst = arith.constant 0.000000e+00 : f32 loc(#loc203)
    %c256_i32 = arith.constant 256 : i32 loc(#loc2)
    %c0_i32 = arith.constant 0 : i32 loc(#loc204)
    %true = arith.constant true loc(#loc205)
    %alloca = memref.alloca() : memref<1xf32> loc(#loc206)
    %0 = "polygeist.undef"() : () -> f32 loc(#loc206)
    affine.store %0, %alloca[0] : memref<1xf32> loc(#loc206)
    %alloca_0 = memref.alloca() : memref<1xi32> loc(#loc207)
    %1 = "polygeist.undef"() : () -> i32 loc(#loc207)
    affine.store %1, %alloca_0[0] : memref<1xi32> loc(#loc207)
    %alloca_1 = memref.alloca() : memref<1xf32> loc(#loc208)
    affine.store %0, %alloca_1[0] : memref<1xf32> loc(#loc208)
    %alloca_2 = memref.alloca() : memref<1xi32> loc(#loc209)
    affine.store %1, %alloca_2[0] : memref<1xi32> loc(#loc209)
    %alloca_3 = memref.alloca() : memref<1xf32> loc(#loc210)
    affine.store %0, %alloca_3[0] : memref<1xf32> loc(#loc210)
    %alloca_4 = memref.alloca() : memref<1xi32> loc(#loc211)
    affine.store %1, %alloca_4[0] : memref<1xi32> loc(#loc211)
    %alloca_5 = memref.alloca() : memref<1xf32> loc(#loc212)
    affine.store %0, %alloca_5[0] : memref<1xf32> loc(#loc212)
    %alloca_6 = memref.alloca() : memref<1xi32> loc(#loc213)
    affine.store %1, %alloca_6[0] : memref<1xi32> loc(#loc213)
    %alloca_7 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc214)
    %alloca_8 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc215)
    %alloca_9 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc216)
    %alloca_10 = memref.alloca() : memref<1xmemref<?xi8>> loc(#loc217)
    %alloca_11 = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc218)
    %alloca_12 = memref.alloca() : memref<1xmemref<?xi32>> loc(#loc219)
    %alloca_13 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc220)
    %alloca_14 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc221)
    %alloca_15 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc222)
    %alloca_16 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc223)
    %alloca_17 = memref.alloca() : memref<1xi32> loc(#loc224)
    affine.store %1, %alloca_17[0] : memref<1xi32> loc(#loc224)
    %alloca_18 = memref.alloca() : memref<1xi32> loc(#loc225)
    affine.store %1, %alloca_18[0] : memref<1xi32> loc(#loc225)
    %alloca_19 = memref.alloca() : memref<1xi32> loc(#loc226)
    affine.store %1, %alloca_19[0] : memref<1xi32> loc(#loc226)
    affine.store %arg0, %alloca_19[0] : memref<1xi32> loc(#loc226)
    affine.store %arg1, %alloca_18[0] : memref<1xi32> loc(#loc225)
    affine.store %arg2, %alloca_17[0] : memref<1xi32> loc(#loc224)
    affine.store %arg3, %alloca_16[0] : memref<1xmemref<?xf32>> loc(#loc223)
    affine.store %arg4, %alloca_15[0] : memref<1xmemref<?xf32>> loc(#loc222)
    affine.store %arg5, %alloca_14[0] : memref<1xmemref<?xf32>> loc(#loc221)
    affine.store %arg6, %alloca_13[0] : memref<1xmemref<?xf32>> loc(#loc220)
    affine.store %arg7, %alloca_12[0] : memref<1xmemref<?xi32>> loc(#loc219)
    affine.store %arg8, %alloca_11[0] : memref<1xmemref<?xi32>> loc(#loc218)
    affine.store %arg9, %alloca_10[0] : memref<1xmemref<?xi8>> loc(#loc217)
    affine.store %arg10, %alloca_9[0] : memref<1xmemref<?xf32>> loc(#loc216)
    affine.store %arg11, %alloca_8[0] : memref<1xmemref<?xf32>> loc(#loc215)
    affine.store %arg12, %alloca_7[0] : memref<1xmemref<?xf32>> loc(#loc214)
    scf.if %true {
      scf.execute_region {
        scf.if %true {
          scf.execute_region {
            %2 = affine.load %alloca_19[0] : memref<1xi32> loc(#loc204)
            %3 = arith.cmpi ne, %2, %c0_i32 : i32 loc(#loc204)
            scf.if %3 {
              scf.if %true {
                scf.execute_region {
                  cf.br ^bb1 loc(#loc228)
                ^bb1:  // pred: ^bb0
                  cf.br ^bb2 loc(#loc229)
                ^bb2:  // pred: ^bb1
                  scf.if %true {
                    scf.execute_region {
                      scf.if %true {
                        scf.execute_region {
                          affine.store %c0_i32, %alloca_6[0] : memref<1xi32> loc(#loc213)
                          scf.yield loc(#loc)
                        } loc(#loc)
                      } loc(#loc)
                      scf.while : () -> () {
                        %4 = affine.load %alloca_6[0] : memref<1xi32> loc(#loc230)
                        %5 = arith.cmpi slt, %4, %c256_i32 : i32 loc(#loc231)
                        scf.condition(%5) loc(#loc232)
                      } do {
                        scf.if %true {
                          scf.execute_region {
                            scf.if %true {
                              scf.execute_region {
                                affine.store %cst, %alloca_5[0] : memref<1xf32> loc(#loc212)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            cf.br ^bb1 loc(#loc233)
                          ^bb1:  // pred: ^bb0
                            cf.br ^bb2 loc(#loc234)
                          ^bb2:  // pred: ^bb1
                            scf.if %true {
                              scf.execute_region {
                                scf.if %true {
                                  scf.execute_region {
                                    affine.store %c0_i32, %alloca_4[0] : memref<1xi32> loc(#loc211)
                                    scf.yield loc(#loc)
                                  } loc(#loc)
                                } loc(#loc)
                                scf.while : () -> () {
                                  %4 = affine.load %alloca_4[0] : memref<1xi32> loc(#loc235)
                                  %5 = arith.cmpi slt, %4, %c200_i32 : i32 loc(#loc236)
                                  scf.condition(%5) loc(#loc237)
                                } do {
                                  scf.if %true {
                                    scf.execute_region {
                                      scf.if %true {
                                        scf.execute_region {
                                          %4 = affine.load %alloca_16[0] : memref<1xmemref<?xf32>> loc(#loc238)
                                          %5 = affine.load %alloca_6[0] : memref<1xi32> loc(#loc239)
                                          %6 = arith.muli %5, %c200_i32 : i32 loc(#loc240)
                                          %7 = affine.load %alloca_4[0] : memref<1xi32> loc(#loc241)
                                          %8 = arith.addi %6, %7 : i32 loc(#loc242)
                                          %9 = arith.index_cast %8 : i32 to index loc(#loc243)
                                          %10 = "polygeist.subindex"(%4, %9) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc238)
                                          %11 = affine.load %10[0] : memref<?xf32> loc(#loc238)
                                          %12 = affine.load %alloca_14[0] : memref<1xmemref<?xf32>> loc(#loc244)
                                          %13 = arith.index_cast %7 : i32 to index loc(#loc245)
                                          %14 = "polygeist.subindex"(%12, %13) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc244)
                                          %15 = affine.load %14[0] : memref<?xf32> loc(#loc244)
                                          %16 = arith.subf %11, %15 : f32 loc(#loc246)
                                          affine.store %16, %alloca_3[0] : memref<1xf32> loc(#loc210)
                                          scf.yield loc(#loc)
                                        } loc(#loc)
                                      } loc(#loc)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                  scf.if %true {
                                    scf.execute_region {
                                      %4 = affine.load %alloca_3[0] : memref<1xf32> loc(#loc247)
                                      %5 = arith.mulf %4, %4 : f32 loc(#loc248)
                                      %6 = affine.load %alloca_5[0] : memref<1xf32> loc(#loc249)
                                      %7 = arith.addf %6, %5 : f32 loc(#loc249)
                                      affine.store %7, %alloca_5[0] : memref<1xf32> loc(#loc249)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                  scf.if %true {
                                    scf.execute_region {
                                      %4 = affine.load %alloca_4[0] : memref<1xi32> loc(#loc202)
                                      %5 = arith.addi %4, %c1_i32 : i32 loc(#loc202)
                                      affine.store %5, %alloca_4[0] : memref<1xi32> loc(#loc202)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                  scf.yield loc(#loc237)
                                } loc(#loc235)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            %4 = affine.load %alloca_7[0] : memref<1xmemref<?xf32>> loc(#loc250)
                            %5 = affine.load %alloca_6[0] : memref<1xi32> loc(#loc251)
                            %6 = arith.index_cast %5 : i32 to index loc(#loc252)
                            %7 = "polygeist.subindex"(%4, %6) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc250)
                            %8 = affine.load %alloca_5[0] : memref<1xf32> loc(#loc253)
                            %9 = affine.load %alloca_15[0] : memref<1xmemref<?xf32>> loc(#loc254)
                            %10 = "polygeist.subindex"(%9, %6) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc254)
                            %11 = affine.load %10[0] : memref<?xf32> loc(#loc254)
                            %12 = arith.mulf %8, %11 : f32 loc(#loc255)
                            affine.store %12, %7[0] : memref<?xf32> loc(#loc256)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            %4 = affine.load %alloca_6[0] : memref<1xi32> loc(#loc257)
                            %5 = arith.addi %4, %c1_i32 : i32 loc(#loc257)
                            affine.store %5, %alloca_6[0] : memref<1xi32> loc(#loc257)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.yield loc(#loc232)
                      } loc(#loc230)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
              scf.if %true {
                scf.execute_region {
                  cf.br ^bb1 loc(#loc258)
                ^bb1:  // pred: ^bb0
                  cf.br ^bb2 loc(#loc259)
                ^bb2:  // pred: ^bb1
                  scf.if %true {
                    scf.execute_region {
                      scf.if %true {
                        scf.execute_region {
                          affine.store %c0_i32, %alloca_2[0] : memref<1xi32> loc(#loc209)
                          scf.yield loc(#loc)
                        } loc(#loc)
                      } loc(#loc)
                      scf.while : () -> () {
                        %4 = affine.load %alloca_2[0] : memref<1xi32> loc(#loc260)
                        %5 = arith.cmpi slt, %4, %c256_i32 : i32 loc(#loc261)
                        scf.condition(%5) loc(#loc262)
                      } do {
                        scf.if %true {
                          scf.execute_region {
                            scf.if %true {
                              scf.execute_region {
                                %4 = affine.load %alloca_7[0] : memref<1xmemref<?xf32>> loc(#loc263)
                                %5 = affine.load %alloca_2[0] : memref<1xi32> loc(#loc264)
                                %6 = arith.index_cast %5 : i32 to index loc(#loc265)
                                %7 = "polygeist.subindex"(%4, %6) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc263)
                                %8 = affine.load %7[0] : memref<?xf32> loc(#loc263)
                                %9 = affine.load %alloca_13[0] : memref<1xmemref<?xf32>> loc(#loc266)
                                %10 = "polygeist.subindex"(%9, %6) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc266)
                                %11 = affine.load %10[0] : memref<?xf32> loc(#loc266)
                                %12 = arith.subf %8, %11 : f32 loc(#loc267)
                                affine.store %12, %alloca_1[0] : memref<1xf32> loc(#loc208)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            scf.if %true {
                              scf.execute_region {
                                %4 = affine.load %alloca_11[0] : memref<1xmemref<?xi32>> loc(#loc268)
                                %5 = affine.load %alloca_12[0] : memref<1xmemref<?xi32>> loc(#loc269)
                                %6 = affine.load %alloca_2[0] : memref<1xi32> loc(#loc270)
                                %7 = arith.index_cast %6 : i32 to index loc(#loc271)
                                %8 = "polygeist.subindex"(%5, %7) : (memref<?xi32>, index) -> memref<?xi32> loc(#loc269)
                                %9 = affine.load %8[0] : memref<?xi32> loc(#loc269)
                                %10 = arith.index_cast %9 : i32 to index loc(#loc272)
                                %11 = "polygeist.subindex"(%4, %10) : (memref<?xi32>, index) -> memref<?xi32> loc(#loc268)
                                %12 = affine.load %11[0] : memref<?xi32> loc(#loc268)
                                affine.store %12, %alloca_0[0] : memref<1xi32> loc(#loc207)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            scf.if %true {
                              scf.execute_region {
                                %4 = affine.load %alloca_8[0] : memref<1xmemref<?xf32>> loc(#loc273)
                                %5 = affine.load %alloca_0[0] : memref<1xi32> loc(#loc274)
                                %6 = arith.index_cast %5 : i32 to index loc(#loc275)
                                %7 = "polygeist.subindex"(%4, %6) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc273)
                                %8 = affine.load %7[0] : memref<?xf32> loc(#loc273)
                                %9 = affine.load %alloca_1[0] : memref<1xf32> loc(#loc276)
                                %10 = arith.subf %8, %9 : f32 loc(#loc277)
                                affine.store %10, %alloca[0] : memref<1xf32> loc(#loc206)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            scf.if %true {
                              scf.execute_region {
                                %4 = affine.load %alloca_1[0] : memref<1xf32> loc(#loc278)
                                %5 = arith.cmpf olt, %4, %cst : f32 loc(#loc279)
                                scf.if %5 {
                                  scf.if %true {
                                    scf.execute_region {
                                      %6 = affine.load %alloca_10[0] : memref<1xmemref<?xi8>> loc(#loc281)
                                      %7 = affine.load %alloca_17[0] : memref<1xi32> loc(#loc282)
                                      %8 = affine.load %alloca_2[0] : memref<1xi32> loc(#loc283)
                                      %9 = arith.addi %7, %8 : i32 loc(#loc284)
                                      %10 = arith.index_cast %9 : i32 to index loc(#loc285)
                                      %11 = "polygeist.subindex"(%6, %10) : (memref<?xi8>, index) -> memref<?xi8> loc(#loc281)
                                      affine.store %c1_i8, %11[0] : memref<?xi8> loc(#loc286)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                  scf.if %true {
                                    scf.execute_region {
                                      %6 = affine.load %alloca_9[0] : memref<1xmemref<?xf32>> loc(#loc287)
                                      %7 = affine.load %alloca_1[0] : memref<1xf32> loc(#loc288)
                                      %8 = affine.load %6[0] : memref<?xf32> loc(#loc289)
                                      %9 = arith.addf %8, %7 : f32 loc(#loc289)
                                      affine.store %9, %6[0] : memref<?xf32> loc(#loc289)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                } else {
                                  scf.if %true {
                                    scf.execute_region {
                                      %6 = affine.load %alloca_8[0] : memref<1xmemref<?xf32>> loc(#loc290)
                                      %7 = affine.load %alloca_0[0] : memref<1xi32> loc(#loc291)
                                      %8 = arith.index_cast %7 : i32 to index loc(#loc292)
                                      %9 = "polygeist.subindex"(%6, %8) : (memref<?xf32>, index) -> memref<?xf32> loc(#loc290)
                                      %10 = affine.load %alloca[0] : memref<1xf32> loc(#loc293)
                                      affine.store %10, %9[0] : memref<?xf32> loc(#loc294)
                                      scf.yield loc(#loc)
                                    } loc(#loc)
                                  } loc(#loc)
                                } loc(#loc280)
                                scf.yield loc(#loc)
                              } loc(#loc)
                            } loc(#loc)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.if %true {
                          scf.execute_region {
                            %4 = affine.load %alloca_2[0] : memref<1xi32> loc(#loc295)
                            %5 = arith.addi %4, %c1_i32 : i32 loc(#loc295)
                            affine.store %5, %alloca_2[0] : memref<1xi32> loc(#loc295)
                            scf.yield loc(#loc)
                          } loc(#loc)
                        } loc(#loc)
                        scf.yield loc(#loc262)
                      } loc(#loc260)
                      scf.yield loc(#loc)
                    } loc(#loc)
                  } loc(#loc)
                  scf.yield loc(#loc)
                } loc(#loc)
              } loc(#loc)
            } loc(#loc227)
            scf.yield loc(#loc)
          } loc(#loc)
        } loc(#loc)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc296)
  } loc(#loc200)
  func.func @store(%arg0: i32 loc("streamcluster.cpp":44:6), %arg1: i32 loc("streamcluster.cpp":44:6), %arg2: memref<?xf32> loc("streamcluster.cpp":44:6), %arg3: memref<?xi8> loc("streamcluster.cpp":44:6), %arg4: memref<?xf32> loc("streamcluster.cpp":44:6), %arg5: memref<?xf32> loc("streamcluster.cpp":44:6), %arg6: memref<?xi8> loc("streamcluster.cpp":44:6), %arg7: memref<?xf32> loc("streamcluster.cpp":44:6)) attributes {llvm.linkage = #llvm.linkage<external>} {
    %c1024_i64 = arith.constant 1024 : i64 loc(#loc4)
    %true = arith.constant true loc(#loc298)
    %alloca = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc299)
    %alloca_0 = memref.alloca() : memref<1xmemref<?xi8>> loc(#loc300)
    %alloca_1 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc301)
    %alloca_2 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc302)
    %alloca_3 = memref.alloca() : memref<1xmemref<?xi8>> loc(#loc303)
    %alloca_4 = memref.alloca() : memref<1xmemref<?xf32>> loc(#loc304)
    %alloca_5 = memref.alloca() : memref<1xi32> loc(#loc305)
    %0 = "polygeist.undef"() : () -> i32 loc(#loc305)
    affine.store %0, %alloca_5[0] : memref<1xi32> loc(#loc305)
    %alloca_6 = memref.alloca() : memref<1xi32> loc(#loc306)
    affine.store %0, %alloca_6[0] : memref<1xi32> loc(#loc306)
    affine.store %arg0, %alloca_6[0] : memref<1xi32> loc(#loc306)
    affine.store %arg1, %alloca_5[0] : memref<1xi32> loc(#loc305)
    affine.store %arg2, %alloca_4[0] : memref<1xmemref<?xf32>> loc(#loc304)
    affine.store %arg3, %alloca_3[0] : memref<1xmemref<?xi8>> loc(#loc303)
    affine.store %arg4, %alloca_2[0] : memref<1xmemref<?xf32>> loc(#loc302)
    affine.store %arg5, %alloca_1[0] : memref<1xmemref<?xf32>> loc(#loc301)
    affine.store %arg6, %alloca_0[0] : memref<1xmemref<?xi8>> loc(#loc300)
    affine.store %arg7, %alloca[0] : memref<1xmemref<?xf32>> loc(#loc299)
    scf.if %true {
      scf.execute_region {
        %1 = affine.load %alloca_4[0] : memref<1xmemref<?xf32>> loc(#loc307)
        %2 = "polygeist.memref2pointer"(%1) : (memref<?xf32>) -> !llvm.ptr loc(#loc307)
        %3 = affine.load %alloca_1[0] : memref<1xmemref<?xf32>> loc(#loc308)
        %4 = "polygeist.memref2pointer"(%3) : (memref<?xf32>) -> !llvm.ptr loc(#loc308)
        %5 = "polygeist.typeSize"() <{source = f32}> : () -> index loc(#loc309)
        %6 = arith.index_cast %5 : index to i64 loc(#loc309)
        %7 = arith.muli %6, %c1024_i64 : i64 loc(#loc310)
        "llvm.intr.memcpy"(%2, %4, %7) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc311)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = affine.load %alloca_3[0] : memref<1xmemref<?xi8>> loc(#loc312)
        %2 = "polygeist.memref2pointer"(%1) : (memref<?xi8>) -> !llvm.ptr loc(#loc312)
        %3 = affine.load %alloca_0[0] : memref<1xmemref<?xi8>> loc(#loc313)
        %4 = "polygeist.memref2pointer"(%3) : (memref<?xi8>) -> !llvm.ptr loc(#loc313)
        %5 = "polygeist.typeSize"() <{source = i8}> : () -> index loc(#loc314)
        %6 = arith.index_cast %5 : index to i64 loc(#loc314)
        %7 = arith.muli %6, %c1024_i64 : i64 loc(#loc315)
        "llvm.intr.memcpy"(%2, %4, %7) <{isVolatile = false}> : (!llvm.ptr, !llvm.ptr, i64) -> () loc(#loc316)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    scf.if %true {
      scf.execute_region {
        %1 = affine.load %alloca_2[0] : memref<1xmemref<?xf32>> loc(#loc317)
        %2 = affine.load %alloca[0] : memref<1xmemref<?xf32>> loc(#loc318)
        %3 = affine.load %2[0] : memref<?xf32> loc(#loc318)
        affine.store %3, %1[0] : memref<?xf32> loc(#loc319)
        scf.yield loc(#loc)
      } loc(#loc)
    } loc(#loc)
    return loc(#loc320)
  } loc(#loc297)
} loc(#loc)
#loc = loc(unknown)
#loc2 = loc("streamcluster.cpp":2:18)
#loc3 = loc("streamcluster.cpp":118:21)
#loc4 = loc("./streamcluster.h":10:20)
#loc5 = loc("streamcluster.cpp":114:44)
#loc6 = loc("streamcluster.cpp":114:26)
#loc7 = loc("./streamcluster.h":9:13)
#loc8 = loc("streamcluster.cpp":51:1)
#loc9 = loc("streamcluster.cpp":116:3)
#loc10 = loc("streamcluster.cpp":115:3)
#loc11 = loc("streamcluster.cpp":114:18)
#loc12 = loc("streamcluster.cpp":105:6)
#loc13 = loc("streamcluster.cpp":104:6)
#loc14 = loc("streamcluster.cpp":103:6)
#loc15 = loc("streamcluster.cpp":102:6)
#loc16 = loc("streamcluster.cpp":100:6)
#loc17 = loc("streamcluster.cpp":99:6)
#loc18 = loc("streamcluster.cpp":98:6)
#loc19 = loc("streamcluster.cpp":97:6)
#loc20 = loc("streamcluster.cpp":95:5)
#loc21 = loc("streamcluster.cpp":92:5)
#loc22 = loc("streamcluster.cpp":91:5)
#loc23 = loc("streamcluster.cpp":90:5)
#loc24 = loc("streamcluster.cpp":89:5)
#loc25 = loc("streamcluster.cpp":88:5)
#loc26 = loc("streamcluster.cpp":62:5)
#loc27 = loc("streamcluster.cpp":61:5)
#loc28 = loc("streamcluster.cpp":60:5)
#loc29 = loc("streamcluster.cpp":59:5)
#loc30 = loc("streamcluster.cpp":58:5)
#loc31 = loc("streamcluster.cpp":57:5)
#loc32 = loc("streamcluster.cpp":56:5)
#loc33 = loc("streamcluster.cpp":55:5)
#loc34 = loc("streamcluster.cpp":54:5)
#loc35 = loc("streamcluster.cpp":53:5)
#loc36 = loc("streamcluster.cpp":52:5)
#loc37 = loc("streamcluster.cpp":88:1)
#loc38 = loc("streamcluster.cpp":89:1)
#loc39 = loc("streamcluster.cpp":90:1)
#loc40 = loc("streamcluster.cpp":91:1)
#loc41 = loc("streamcluster.cpp":92:1)
#loc42 = loc("streamcluster.cpp":93:32)
#loc43 = loc("streamcluster.cpp":93:30)
#loc44 = loc("streamcluster.cpp":95:1)
#loc45 = loc("streamcluster.cpp":97:1)
#loc46 = loc("streamcluster.cpp":98:1)
#loc47 = loc("streamcluster.cpp":99:1)
#loc48 = loc("streamcluster.cpp":100:1)
#loc49 = loc("streamcluster.cpp":102:1)
#loc50 = loc("streamcluster.cpp":103:1)
#loc51 = loc("streamcluster.cpp":104:1)
#loc52 = loc("streamcluster.cpp":105:1)
#loc53 = loc("streamcluster.cpp":108:9)
#loc54 = loc("streamcluster.cpp":108:26)
#loc55 = loc("streamcluster.cpp":108:49)
#loc56 = loc("streamcluster.cpp":108:47)
#loc57 = loc("streamcluster.cpp":108:2)
#loc58 = loc("streamcluster.cpp":109:9)
#loc59 = loc("streamcluster.cpp":109:35)
#loc60 = loc("streamcluster.cpp":109:67)
#loc61 = loc("streamcluster.cpp":109:65)
#loc62 = loc("streamcluster.cpp":109:2)
#loc63 = loc("streamcluster.cpp":111:9)
#loc64 = loc("streamcluster.cpp":111:24)
#loc65 = loc("streamcluster.cpp":111:38)
#loc66 = loc("streamcluster.cpp":111:36)
#loc67 = loc("streamcluster.cpp":111:2)
#loc68 = loc("streamcluster.cpp":112:9)
#loc69 = loc("streamcluster.cpp":112:30)
#loc70 = loc("streamcluster.cpp":112:57)
#loc71 = loc("streamcluster.cpp":112:55)
#loc72 = loc("streamcluster.cpp":112:2)
#loc73 = loc("streamcluster.cpp":114:1)
#loc74 = loc("streamcluster.cpp":114:6)
#loc75 = loc("streamcluster.cpp":114:29)
#loc76 = loc("streamcluster.cpp":114:31)
#loc77 = loc("streamcluster.cpp":114:14)
#loc78 = loc("streamcluster.cpp":115:19)
#loc79 = loc("streamcluster.cpp":115:21)
#loc80 = loc("streamcluster.cpp":115:26)
#loc81 = loc("streamcluster.cpp":115:29)
#loc82 = loc("streamcluster.cpp":115:31)
#loc83 = loc("streamcluster.cpp":116:22)
#loc84 = loc("streamcluster.cpp":116:24)
#loc85 = loc("streamcluster.cpp":116:36)
#loc86 = loc("streamcluster.cpp":116:39)
#loc87 = loc("streamcluster.cpp":116:41)
#loc88 = loc("streamcluster.cpp":118:7)
#loc89 = loc("streamcluster.cpp":118:8)
#loc90 = loc("streamcluster.cpp":118:19)
#loc91 = loc("streamcluster.cpp":118:23)
#loc92 = loc("streamcluster.cpp":118:3)
#loc93 = loc("streamcluster.cpp":119:9)
#loc94 = loc("streamcluster.cpp":119:20)
#loc95 = loc("streamcluster.cpp":119:23)
#loc96 = loc("streamcluster.cpp":119:30)
#loc97 = loc("streamcluster.cpp":119:38)
#loc98 = loc("streamcluster.cpp":119:44)
#loc99 = loc("streamcluster.cpp":119:52)
#loc100 = loc("streamcluster.cpp":119:68)
#loc101 = loc("streamcluster.cpp":119:85)
#loc102 = loc("streamcluster.cpp":119:100)
#loc103 = loc("streamcluster.cpp":119:4)
#loc104 = loc("streamcluster.cpp":120:12)
#loc105 = loc("streamcluster.cpp":120:26)
#loc106 = loc("streamcluster.cpp":120:31)
#loc107 = loc("streamcluster.cpp":120:33)
#loc108 = loc("streamcluster.cpp":120:45)
#loc109 = loc("streamcluster.cpp":120:61)
#loc110 = loc("streamcluster.cpp":120:78)
#loc111 = loc("streamcluster.cpp":120:93)
#loc112 = loc("streamcluster.cpp":120:108)
#loc113 = loc("streamcluster.cpp":121:6)
#loc114 = loc("streamcluster.cpp":121:27)
#loc115 = loc("streamcluster.cpp":121:53)
#loc116 = loc("streamcluster.cpp":121:79)
#loc117 = loc("streamcluster.cpp":121:96)
#loc118 = loc("streamcluster.cpp":120:4)
#loc119 = loc("streamcluster.cpp":123:9)
#loc120 = loc("streamcluster.cpp":123:20)
#loc121 = loc("streamcluster.cpp":123:23)
#loc122 = loc("streamcluster.cpp":123:30)
#loc123 = loc("streamcluster.cpp":123:38)
#loc124 = loc("streamcluster.cpp":123:44)
#loc125 = loc("streamcluster.cpp":123:52)
#loc126 = loc("streamcluster.cpp":123:68)
#loc127 = loc("streamcluster.cpp":123:85)
#loc128 = loc("streamcluster.cpp":123:100)
#loc129 = loc("streamcluster.cpp":123:4)
#loc130 = loc("streamcluster.cpp":124:12)
#loc131 = loc("streamcluster.cpp":124:26)
#loc132 = loc("streamcluster.cpp":124:31)
#loc133 = loc("streamcluster.cpp":124:33)
#loc134 = loc("streamcluster.cpp":124:45)
#loc135 = loc("streamcluster.cpp":124:61)
#loc136 = loc("streamcluster.cpp":124:78)
#loc137 = loc("streamcluster.cpp":124:93)
#loc138 = loc("streamcluster.cpp":124:108)
#loc139 = loc("streamcluster.cpp":125:6)
#loc140 = loc("streamcluster.cpp":125:27)
#loc141 = loc("streamcluster.cpp":125:53)
#loc142 = loc("streamcluster.cpp":125:79)
#loc143 = loc("streamcluster.cpp":125:96)
#loc144 = loc("streamcluster.cpp":124:4)
#loc145 = loc("streamcluster.cpp":114:58)
#loc146 = loc("streamcluster.cpp":130:8)
#loc147 = loc("streamcluster.cpp":130:13)
#loc148 = loc("streamcluster.cpp":130:24)
#loc149 = loc("streamcluster.cpp":130:34)
#loc150 = loc("streamcluster.cpp":130:53)
#loc151 = loc("streamcluster.cpp":131:3)
#loc152 = loc("streamcluster.cpp":131:20)
#loc153 = loc("streamcluster.cpp":131:46)
#loc154 = loc("streamcluster.cpp":130:2)
#loc155 = loc("streamcluster.cpp":134:1)
#loc157 = loc("streamcluster.cpp":8:5)
#loc158 = loc("streamcluster.cpp":6:1)
#loc159 = loc("streamcluster.cpp":7:67)
#loc160 = loc("streamcluster.cpp":7:47)
#loc161 = loc("streamcluster.cpp":7:25)
#loc162 = loc("streamcluster.cpp":7:4)
#loc163 = loc("streamcluster.cpp":6:70)
#loc164 = loc("streamcluster.cpp":6:57)
#loc165 = loc("streamcluster.cpp":6:42)
#loc166 = loc("streamcluster.cpp":6:28)
#loc167 = loc("streamcluster.cpp":6:21)
#loc168 = loc("streamcluster.cpp":6:11)
#loc169 = loc("streamcluster.cpp":8:2)
#loc170 = loc("streamcluster.cpp":9:10)
#loc171 = loc("streamcluster.cpp":9:24)
#loc172 = loc("streamcluster.cpp":9:32)
#loc173 = loc("streamcluster.cpp":9:34)
#loc174 = loc("streamcluster.cpp":9:30)
#loc175 = loc("streamcluster.cpp":9:58)
#loc176 = loc("streamcluster.cpp":9:56)
#loc177 = loc("streamcluster.cpp":9:3)
#loc178 = loc("streamcluster.cpp":10:10)
#loc179 = loc("streamcluster.cpp":10:25)
#loc180 = loc("streamcluster.cpp":10:34)
#loc181 = loc("streamcluster.cpp":10:32)
#loc182 = loc("streamcluster.cpp":10:48)
#loc183 = loc("streamcluster.cpp":10:46)
#loc184 = loc("streamcluster.cpp":10:3)
#loc185 = loc("streamcluster.cpp":11:10)
#loc186 = loc("streamcluster.cpp":11:23)
#loc187 = loc("streamcluster.cpp":11:30)
#loc188 = loc("streamcluster.cpp":11:28)
#loc189 = loc("streamcluster.cpp":11:44)
#loc190 = loc("streamcluster.cpp":11:42)
#loc191 = loc("streamcluster.cpp":11:3)
#loc192 = loc("streamcluster.cpp":12:10)
#loc193 = loc("streamcluster.cpp":12:25)
#loc194 = loc("streamcluster.cpp":12:34)
#loc195 = loc("streamcluster.cpp":12:32)
#loc196 = loc("streamcluster.cpp":12:48)
#loc197 = loc("streamcluster.cpp":12:46)
#loc198 = loc("streamcluster.cpp":12:3)
#loc199 = loc("streamcluster.cpp":14:1)
#loc201 = loc("streamcluster.cpp":35:32)
#loc202 = loc("streamcluster.cpp":23:42)
#loc203 = loc("streamcluster.cpp":22:16)
#loc204 = loc("streamcluster.cpp":19:5)
#loc205 = loc("streamcluster.cpp":17:1)
#loc206 = loc("streamcluster.cpp":33:4)
#loc207 = loc("streamcluster.cpp":32:4)
#loc208 = loc("streamcluster.cpp":31:4)
#loc209 = loc("streamcluster.cpp":30:16)
#loc210 = loc("streamcluster.cpp":24:5)
#loc211 = loc("streamcluster.cpp":23:21)
#loc212 = loc("streamcluster.cpp":22:4)
#loc213 = loc("streamcluster.cpp":20:14)
#loc214 = loc("streamcluster.cpp":18:90)
#loc215 = loc("streamcluster.cpp":18:73)
#loc216 = loc("streamcluster.cpp":18:47)
#loc217 = loc("streamcluster.cpp":18:22)
#loc218 = loc("streamcluster.cpp":18:3)
#loc219 = loc("streamcluster.cpp":17:97)
#loc220 = loc("streamcluster.cpp":17:84)
#loc221 = loc("streamcluster.cpp":17:69)
#loc222 = loc("streamcluster.cpp":17:54)
#loc223 = loc("streamcluster.cpp":17:40)
#loc224 = loc("streamcluster.cpp":17:33)
#loc225 = loc("streamcluster.cpp":17:24)
#loc226 = loc("streamcluster.cpp":17:14)
#loc227 = loc("streamcluster.cpp":19:2)
#loc228 = loc("streamcluster.cpp":20:1)
#loc229 = loc("streamcluster.cpp":20:6)
#loc230 = loc("streamcluster.cpp":20:25)
#loc231 = loc("streamcluster.cpp":20:27)
#loc232 = loc("streamcluster.cpp":20:10)
#loc233 = loc("streamcluster.cpp":23:1)
#loc234 = loc("streamcluster.cpp":23:7)
#loc235 = loc("streamcluster.cpp":23:32)
#loc236 = loc("streamcluster.cpp":23:34)
#loc237 = loc("streamcluster.cpp":23:17)
#loc238 = loc("streamcluster.cpp":24:15)
#loc239 = loc("streamcluster.cpp":24:21)
#loc240 = loc("streamcluster.cpp":24:23)
#loc241 = loc("streamcluster.cpp":24:31)
#loc242 = loc("streamcluster.cpp":24:29)
#loc243 = loc("streamcluster.cpp":24:32)
#loc244 = loc("streamcluster.cpp":24:36)
#loc245 = loc("streamcluster.cpp":24:44)
#loc246 = loc("streamcluster.cpp":24:34)
#loc247 = loc("streamcluster.cpp":25:12)
#loc248 = loc("streamcluster.cpp":25:14)
#loc249 = loc("streamcluster.cpp":25:9)
#loc250 = loc("streamcluster.cpp":27:4)
#loc251 = loc("streamcluster.cpp":27:11)
#loc252 = loc("streamcluster.cpp":27:12)
#loc253 = loc("streamcluster.cpp":27:16)
#loc254 = loc("streamcluster.cpp":27:22)
#loc255 = loc("streamcluster.cpp":27:20)
#loc256 = loc("streamcluster.cpp":27:14)
#loc257 = loc("streamcluster.cpp":20:40)
#loc258 = loc("streamcluster.cpp":30:1)
#loc259 = loc("streamcluster.cpp":30:6)
#loc260 = loc("streamcluster.cpp":30:27)
#loc261 = loc("streamcluster.cpp":30:29)
#loc262 = loc("streamcluster.cpp":30:12)
#loc263 = loc("streamcluster.cpp":31:25)
#loc264 = loc("streamcluster.cpp":31:32)
#loc265 = loc("streamcluster.cpp":31:33)
#loc266 = loc("streamcluster.cpp":31:37)
#loc267 = loc("streamcluster.cpp":31:35)
#loc268 = loc("streamcluster.cpp":32:29)
#loc269 = loc("streamcluster.cpp":32:42)
#loc270 = loc("streamcluster.cpp":32:49)
#loc271 = loc("streamcluster.cpp":32:50)
#loc272 = loc("streamcluster.cpp":32:51)
#loc273 = loc("streamcluster.cpp":33:26)
#loc274 = loc("streamcluster.cpp":33:35)
#loc275 = loc("streamcluster.cpp":33:53)
#loc276 = loc("streamcluster.cpp":33:57)
#loc277 = loc("streamcluster.cpp":33:55)
#loc278 = loc("streamcluster.cpp":34:7)
#loc279 = loc("streamcluster.cpp":34:20)
#loc280 = loc("streamcluster.cpp":34:4)
#loc281 = loc("streamcluster.cpp":35:5)
#loc282 = loc("streamcluster.cpp":35:23)
#loc283 = loc("streamcluster.cpp":35:27)
#loc284 = loc("streamcluster.cpp":35:25)
#loc285 = loc("streamcluster.cpp":35:28)
#loc286 = loc("streamcluster.cpp":35:30)
#loc287 = loc("streamcluster.cpp":36:5)
#loc288 = loc("streamcluster.cpp":36:29)
#loc289 = loc("streamcluster.cpp":36:26)
#loc290 = loc("streamcluster.cpp":38:5)
#loc291 = loc("streamcluster.cpp":38:14)
#loc292 = loc("streamcluster.cpp":38:32)
#loc293 = loc("streamcluster.cpp":38:36)
#loc294 = loc("streamcluster.cpp":38:34)
#loc295 = loc("streamcluster.cpp":30:42)
#loc296 = loc("streamcluster.cpp":42:1)
#loc298 = loc("streamcluster.cpp":44:1)
#loc299 = loc("streamcluster.cpp":45:60)
#loc300 = loc("streamcluster.cpp":45:28)
#loc301 = loc("streamcluster.cpp":45:4)
#loc302 = loc("streamcluster.cpp":44:78)
#loc303 = loc("streamcluster.cpp":44:53)
#loc304 = loc("streamcluster.cpp":44:36)
#loc305 = loc("streamcluster.cpp":44:21)
#loc306 = loc("streamcluster.cpp":44:12)
#loc307 = loc("streamcluster.cpp":46:9)
#loc308 = loc("streamcluster.cpp":46:19)
#loc309 = loc("streamcluster.cpp":46:49)
#loc310 = loc("streamcluster.cpp":46:47)
#loc311 = loc("streamcluster.cpp":46:2)
#loc312 = loc("streamcluster.cpp":47:9)
#loc313 = loc("streamcluster.cpp":47:28)
#loc314 = loc("streamcluster.cpp":47:67)
#loc315 = loc("streamcluster.cpp":47:65)
#loc316 = loc("streamcluster.cpp":47:2)
#loc317 = loc("streamcluster.cpp":48:2)
#loc318 = loc("streamcluster.cpp":48:25)
#loc319 = loc("streamcluster.cpp":48:23)
#loc320 = loc("streamcluster.cpp":49:1)
